from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: TestProject.Generated.Tests.JupyterNotebookFunctionalTest
    Test: In-Browser Editing Features
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/24/2021, 04:23:09
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="In-Browser Editing Features")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder1'
    functional_test_folder1 = driver.find_element(By.XPATH,
                                                  "//span[. = 'functional test folder']")
    functional_test_folder1.click()

    # 3. Click 'test_editor_02.ipynb3'
    test_editor_02_ipynb3 = driver.find_element(By.XPATH,
                                                "//span[. = 'test_editor_02.ipynb']")
    test_editor_02_ipynb3.click()

    # 4. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 5. Type 'print' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("print")

    # 6. Type 'try' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("try")

    # 7. Type 'except' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("except")

    # 8. Type 'assert' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("assert")

    # 9. Type 'open' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("open")

    # 10. Type 'len' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("len")

    # 11. Type 'class' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("class")

    # 12. Type 'def' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("def")

    # 13. Type '@staticmethod' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("@staticmethod")

    # 14. Type '#comment' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("#comment")

    # 15. Type 'if' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("if")

    # 16. Type 'elif' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("elif")

    # 17. Type 'else' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("else")

    # 18. Type 'True' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("True")

    # 19. Type 'False' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("False")

    # 20. Type '""' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("\"\"")

    # 21. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 22. Click 'DIV3'
    div3 = driver.find_element(By.XPATH,
                               "//div[2]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div")
    div3.click()

    # 23. Type 'for i in range(10):
    #     if i % 2 == 0:
    #         print(i, end=" ")' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys(
        "for i in range(10):\n    if i % 2 == 0:\n        print(i, end=\" \")")

    # 24. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 25. Click 'if'
    _if = driver.find_element(By.XPATH,
                              "//div[3]//span[. = 'if']")
    _if.click()

    # 26. Click 'print1'
    print1 = driver.find_element(By.XPATH,
                                 "//div[3]/div//span[. = 'print']")
    print1.click()

    # 27. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 28. Type 'class Animal:
    #     def __init__(self, name, age):
    #         self.name = name
    #         self.age = age' in 'TEXTAREA10'
    textarea10 = driver.find_element(By.XPATH,
                                     "//div[5]//textarea")
    textarea10.send_keys(
        "class Animal:\n    def __init__(self, name, age):\n        self.name = name\n        self.age = age")

    # 29. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 30. Type 'class Dog(Ani' in 'TEXTAREA10'
    textarea10 = driver.find_element(By.XPATH,
                                     "//div[5]//textarea")
    textarea10.send_keys("class Dog(Ani")

    # 31. Send 'TAB' key(s)
    ActionChains(driver).send_keys(Keys.TAB).perform()

    # 32. Type '):' in 'TEXTAREA10'
    textarea10 = driver.find_element(By.XPATH,
                                     "//div[5]//textarea")
    textarea10.send_keys("):")

    # 33. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 34. Type '    def __in' in 'TEXTAREA10'
    textarea10 = driver.find_element(By.XPATH,
                                     "//div[5]//textarea")
    textarea10.send_keys("    def __in")

    # 35. Send 'TAB' key(s)
    ActionChains(driver).send_keys(Keys.TAB).perform()
