from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: TestProject.Generated.Tests.JupyterNotebookFunctionalTest
    Test: Upload Files
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 04/21/2021, 03:35:34
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Upload Files")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://127.0.0.1:8888/?token=4636fe43668233d67fde93f4eef1a508ae550c7c29be077c"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'datafile'
    datafile = driver.find_element(By.CSS_SELECTOR,
                                   "#upload_span_input")
    datafile.click()

    # 3. Click 'Upload'
    upload = driver.find_element(By.XPATH,
                                 "//button[. = 'Upload']")
    upload.click()

    # 4. Click 'datafile'
    datafile = driver.find_element(By.CSS_SELECTOR,
                                   "#upload_span_input")
    datafile.click()

    # 5. Click 'Upload'
    upload = driver.find_element(By.XPATH,
                                 "//button[. = 'Upload']")
    upload.click()

    # 6. Click 'datafile'
    datafile = driver.find_element(By.CSS_SELECTOR,
                                   "#upload_span_input")
    datafile.click()

    # 7. Click 'Upload'
    upload = driver.find_element(By.XPATH,
                                 "//button[. = 'Upload']")
    upload.click()

    # 8. Click 'datafile'
    datafile = driver.find_element(By.CSS_SELECTOR,
                                   "#upload_span_input")
    datafile.click()

    # 9. Click 'Upload'
    upload = driver.find_element(By.XPATH,
                                 "//button[. = 'Upload']")
    upload.click()

    # 10. Click 'datafile'
    datafile = driver.find_element(By.CSS_SELECTOR,
                                   "#upload_span_input")
    datafile.click()

    # 11. Click 'Upload'
    upload = driver.find_element(By.XPATH,
                                 "//button[. = 'Upload']")
    upload.click()

    # 12. Click 'datafile'
    datafile = driver.find_element(By.CSS_SELECTOR,
                                   "#upload_span_input")
    datafile.click()

    # 13. Click 'Upload'
    upload = driver.find_element(By.XPATH,
                                 "//button[. = 'Upload']")
    upload.click()

    # 14. Click 'datafile'
    datafile = driver.find_element(By.CSS_SELECTOR,
                                   "#upload_span_input")
    datafile.click()

    # 15. Click 'Upload'
    upload = driver.find_element(By.XPATH,
                                 "//button[. = 'Upload']")
    upload.click()

    # 16. Click 'datafile'
    datafile = driver.find_element(By.CSS_SELECTOR,
                                   "#upload_span_input")
    datafile.click()

    # 17. Click 'Upload'
    upload = driver.find_element(By.XPATH,
                                 "//button[. = 'Upload']")
    upload.click()

    # 18. Click 'datafile'
    datafile = driver.find_element(By.CSS_SELECTOR,
                                   "#upload_span_input")
    datafile.click()

    # 19. Click 'Upload'
    upload = driver.find_element(By.XPATH,
                                 "//button[. = 'Upload']")
    upload.click()
