from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: TestProject.Generated.Tests.JupyterNotebookFunctionalTest
    Test: Download Files
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/24/2021, 04:02:59
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Download Files")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Click here to rename, delete, etc.7'
    click_here_to_rename_delete_etc_7 = driver.find_element(By.XPATH,
                                                            "//div[43]//input")
    click_here_to_rename_delete_etc_7.click()

    # 3. Click 'Download'
    download = driver.find_element(By.XPATH,
                                   "//button[. = 'Download']")
    download.click()

    # 4. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 5. Close window with index '1'
    driver.close()

    # 6. Switch to window '0'
    driver.switch_to.window(driver.window_handles[0])

    # 7. Click 'Click here to rename, delete, etc.7'
    click_here_to_rename_delete_etc_7 = driver.find_element(By.XPATH,
                                                            "//div[43]//input")
    click_here_to_rename_delete_etc_7.click()

    # 8. Click 'Click here to rename, delete, etc.8'
    click_here_to_rename_delete_etc_8 = driver.find_element(By.XPATH,
                                                            "//div[44]//input")
    click_here_to_rename_delete_etc_8.click()

    # 9. Click 'Download'
    download = driver.find_element(By.XPATH,
                                   "//button[. = 'Download']")
    download.click()

    # 10. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 11. Close window with index '1'
    driver.close()

    # 12. Switch to window '0'
    driver.switch_to.window(driver.window_handles[0])

    # 13. Click 'Click here to rename, delete, etc.8'
    click_here_to_rename_delete_etc_8 = driver.find_element(By.XPATH,
                                                            "//div[44]//input")
    click_here_to_rename_delete_etc_8.click()

    # 14. Click 'Click here to rename, delete, etc.9'
    click_here_to_rename_delete_etc_9 = driver.find_element(By.XPATH,
                                                            "//div[45]//input")
    click_here_to_rename_delete_etc_9.click()

    # 15. Click 'Download'
    download = driver.find_element(By.XPATH,
                                   "//button[. = 'Download']")
    download.click()

    # 16. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 17. Close window with index '1'
    driver.close()

    # 18. Switch to window '0'
    driver.switch_to.window(driver.window_handles[0])

    # 19. Click 'Click here to rename, delete, etc.9'
    click_here_to_rename_delete_etc_9 = driver.find_element(By.XPATH,
                                                            "//div[45]//input")
    click_here_to_rename_delete_etc_9.click()

    # 20. Click 'Click here to rename, delete, etc.10'
    click_here_to_rename_delete_etc_10 = driver.find_element(By.XPATH,
                                                             "//div[46]//input")
    click_here_to_rename_delete_etc_10.click()

    # 21. Click 'Download'
    download = driver.find_element(By.XPATH,
                                   "//button[. = 'Download']")
    download.click()

    # 22. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 23. Close window with index '1'
    driver.close()

    # 24. Switch to window '0'
    driver.switch_to.window(driver.window_handles[0])

    # 25. Click 'DIV21'
    div21 = driver.find_element(By.XPATH,
                                "//div[46]/div")
    div21.click()

    # 26. Click 'Click here to rename, delete, etc.11'
    click_here_to_rename_delete_etc_11 = driver.find_element(By.XPATH,
                                                             "//div[47]//input")
    click_here_to_rename_delete_etc_11.click()

    # 27. Click 'Download'
    download = driver.find_element(By.XPATH,
                                   "//button[. = 'Download']")
    download.click()

    # 28. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 29. Close window with index '1'
    driver.close()

    # 30. Switch to window '0'
    driver.switch_to.window(driver.window_handles[0])

    # 31. Click 'Click here to rename, delete, etc.11'
    click_here_to_rename_delete_etc_11 = driver.find_element(By.XPATH,
                                                             "//div[47]//input")
    click_here_to_rename_delete_etc_11.click()

    # 32. Click 'Click here to rename, delete, etc.12'
    click_here_to_rename_delete_etc_12 = driver.find_element(By.XPATH,
                                                             "//div[48]//input")
    click_here_to_rename_delete_etc_12.click()

    # 33. Click 'Download'
    download = driver.find_element(By.XPATH,
                                   "//button[. = 'Download']")
    download.click()

    # 34. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 35. Close window with index '1'
    driver.close()

    # 36. Switch to window '0'
    driver.switch_to.window(driver.window_handles[0])

    # 37. Click 'Click here to rename, delete, etc.12'
    click_here_to_rename_delete_etc_12 = driver.find_element(By.XPATH,
                                                             "//div[48]//input")
    click_here_to_rename_delete_etc_12.click()

    # 38. Click 'Click here to rename, delete, etc.13'
    click_here_to_rename_delete_etc_13 = driver.find_element(By.XPATH,
                                                             "//div[49]//input")
    click_here_to_rename_delete_etc_13.click()

    # 39. Click 'Download'
    download = driver.find_element(By.XPATH,
                                   "//button[. = 'Download']")
    download.click()

    # 40. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 41. Close window with index '1'
    driver.close()

    # 42. Switch to window '0'
    driver.switch_to.window(driver.window_handles[0])

    # 43. Click 'Click here to rename, delete, etc.14'
    click_here_to_rename_delete_etc_14 = driver.find_element(By.XPATH,
                                                             "//div[50]//input")
    click_here_to_rename_delete_etc_14.click()

    # 44. Click 'Click here to rename, delete, etc.13'
    click_here_to_rename_delete_etc_13 = driver.find_element(By.XPATH,
                                                             "//div[49]//input")
    click_here_to_rename_delete_etc_13.click()

    # 45. Click 'Download'
    download = driver.find_element(By.XPATH,
                                   "//button[. = 'Download']")
    download.click()

    # 46. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 47. Close window with index '1'
    driver.close()

    # 48. Switch to window '0'
    driver.switch_to.window(driver.window_handles[0])

    # 49. Click 'Click here to rename, delete, etc.14'
    click_here_to_rename_delete_etc_14 = driver.find_element(By.XPATH,
                                                             "//div[50]//input")
    click_here_to_rename_delete_etc_14.click()

    # 50. Click 'Click here to rename, delete, etc.15'
    click_here_to_rename_delete_etc_15 = driver.find_element(By.XPATH,
                                                             "//div[51]//input")
    click_here_to_rename_delete_etc_15.click()

    # 51. Click 'Download'
    download = driver.find_element(By.XPATH,
                                   "//button[. = 'Download']")
    download.click()

    # 52. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 53. Close window with index '1'
    driver.close()

    # 54. Switch to window '0'
    driver.switch_to.window(driver.window_handles[0])

    # 55. Click 'Click here to rename, delete, etc.15'
    click_here_to_rename_delete_etc_15 = driver.find_element(By.XPATH,
                                                             "//div[51]//input")
    click_here_to_rename_delete_etc_15.click()

    # 56. Click 'Click here to rename, delete, etc.16'
    click_here_to_rename_delete_etc_16 = driver.find_element(By.XPATH,
                                                             "//div[52]//input")
    click_here_to_rename_delete_etc_16.click()

    # 57. Click 'Download'
    download = driver.find_element(By.XPATH,
                                   "//button[. = 'Download']")
    download.click()

    # 58. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 59. Close window with index '1'
    driver.close()

    # 60. Switch to window '0'
    driver.switch_to.window(driver.window_handles[0])

    # 61. Click 'Click here to rename, delete, etc.16'
    click_here_to_rename_delete_etc_16 = driver.find_element(By.XPATH,
                                                             "//div[52]//input")
    click_here_to_rename_delete_etc_16.click()

    # 62. Click 'Click here to rename, delete, etc.17'
    click_here_to_rename_delete_etc_17 = driver.find_element(By.XPATH,
                                                             "//div[53]//input")
    click_here_to_rename_delete_etc_17.click()

    # 63. Click 'Download'
    download = driver.find_element(By.XPATH,
                                   "//button[. = 'Download']")
    download.click()

    # 64. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 65. Close window with index '1'
    driver.close()

    # 66. Switch to window '0'
    driver.switch_to.window(driver.window_handles[0])
