from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: TestProject.Generated.Tests.JupyterNotebookFunctionalTest
    Test: Running Tab - Terminals Section
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/24/2021, 04:18:25
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Running Tab - Terminals Section")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'tab_content'
    tab_content = driver.find_element(By.CSS_SELECTOR,
                                      "#tab_content")
    tab_content.click()

    # 3. Click 'Running'
    running = driver.find_element(By.XPATH,
                                  "//a[. = 'Running']")
    running.click()

    # 4. Click 'terminals/1'
    terminals_slash_1 = driver.find_element(By.XPATH,
                                            "//span[. = 'terminals/1']")
    terminals_slash_1.click()

    # 5. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 6. Click 'CANVAS'
    canvas = driver.find_element(By.XPATH,
                                 "//canvas[4]")
    canvas.click()

    # 7. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 8. Type ')' in 'TEXTAREA24'
    textarea24 = driver.find_element(By.XPATH,
                                     "//textarea")
    textarea24.send_keys(")")

    # 9. Click 'functional test folder/test_editor_02...'
    functional_test_folder_slash_test_editor_02_ = driver.find_element(By.XPATH,
                                                                       "//span[. = 'functional test folder/test_editor_02.ipynb']")
    functional_test_folder_slash_test_editor_02_.click()

    # 10. Switch to window '2'
    driver.switch_to.window(driver.window_handles[2])

    # 11. Switch to window '0'
    driver.switch_to.window(driver.window_handles[0])

    # 12. Click 'Shutdown3'
    shutdown3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[2]/div/div/div[2]//button[. = 'Shutdown']")
    shutdown3.click()

    # 13. Switch to window '0'
    driver.switch_to.window(driver.window_handles[0])

    # 14. Click 'Shutdown4'
    shutdown4 = driver.find_element(By.XPATH,
                                    "//div[1]/div[2]/div/div/div[2]/div/div/div/button[. = 'Shutdown']")
    shutdown4.click()

    # 15. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])
