from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: TestProject.Generated.Tests.JupyterNotebookFunctionalTest
    Test: Editor Window - Top Section - Rename & Logo
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/05/2021, 12:09:05
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Editor Window - Top Section - Rename & Logo")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'test_editor_02.ipynb1'
    test_editor_02_ipynb1 = driver.find_element(By.XPATH,
                                                "//span[. = 'test_editor_02.ipynb']")
    test_editor_02_ipynb1.click()

    # 4. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 5. Click 'Untitled6'
    untitled6 = driver.find_element(By.CSS_SELECTOR,
                                    "#notebook_name")
    untitled6.click()

    # 6. Click 'Cancel1'
    cancel1 = driver.find_element(By.XPATH,
                                  "//button[. = 'Cancel']")
    cancel1.click()

    # 7. Click 'Untitled6'
    untitled6 = driver.find_element(By.CSS_SELECTOR,
                                    "#notebook_name")
    untitled6.click()

    # 8. Click 'Rename2'
    rename2 = driver.find_element(By.XPATH,
                                  "//button[. = 'Rename']")
    rename2.click()

    # 9. Click 'Untitled6'
    untitled6 = driver.find_element(By.CSS_SELECTOR,
                                    "#notebook_name")
    untitled6.click()

    # 10. Click 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//input")
    input1.click()

    # 11. Type 'test_editor_02_a' in 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//input")
    input1.send_keys("test_editor_02_a")

    # 12. Click 'Rename2'
    rename2 = driver.find_element(By.XPATH,
                                  "//button[. = 'Rename']")
    rename2.click()

    # 13. Click 'Untitled6'
    untitled6 = driver.find_element(By.CSS_SELECTOR,
                                    "#notebook_name")
    untitled6.click()

    # 14. Click 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//input")
    input1.click()

    # 15. Type 'test_editor_01' in 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//input")
    input1.send_keys("test_editor_01")

    # 16. Click 'Rename2'
    rename2 = driver.find_element(By.XPATH,
                                  "//button[. = 'Rename']")
    rename2.click()

    # 17. Click 'Rename2'
    rename2 = driver.find_element(By.XPATH,
                                  "//button[. = 'Rename']")
    rename2.click()

    # 18. Click 'Cancel1'
    cancel1 = driver.find_element(By.XPATH,
                                  "//button[. = 'Cancel']")
    cancel1.click()

    # 19. Click 'Untitled6'
    untitled6 = driver.find_element(By.CSS_SELECTOR,
                                    "#notebook_name")
    untitled6.click()

    # 20. Click 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//input")
    input1.click()

    # 21. Click 'Untitled6'
    untitled6 = driver.find_element(By.CSS_SELECTOR,
                                    "#notebook_name")
    untitled6.click()

    # 22. Click 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//input")
    input1.click()

    # 23. Type 'test_editor_02_~`!@#$%^&*()_-+={}[]|\:;"'<>,.?/' in 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//input")
    input1.send_keys("test_editor_02_~`!@#$%^&*()_-+={}[]|\\:;\"'<>,.?/")

    # 24. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 25. Click 'Cancel1'
    cancel1 = driver.find_element(By.XPATH,
                                  "//button[. = 'Cancel']")
    cancel1.click()

    # 26. Click 'Untitled6'
    untitled6 = driver.find_element(By.CSS_SELECTOR,
                                    "#notebook_name")
    untitled6.click()

    # 27. Click 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//input")
    input1.click()

    # 28. Type 'test_editor_03' in 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//input")
    input1.send_keys("test_editor_03")

    # 29. Click 'Cancel1'
    cancel1 = driver.find_element(By.XPATH,
                                  "//button[. = 'Cancel']")
    cancel1.click()

    # 30. Click 'Untitled6'
    untitled6 = driver.find_element(By.CSS_SELECTOR,
                                    "#notebook_name")
    untitled6.click()

    # 31. Click 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//input")
    input1.click()

    # 32. Type 'test_editor_02^' in 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//input")
    input1.send_keys("test_editor_02^")

    # 33. Click 'Cancel1'
    cancel1 = driver.find_element(By.XPATH,
                                  "//button[. = 'Cancel']")
    cancel1.click()

    # 34. Click 'IMG1'
    img1 = driver.find_element(By.XPATH,
                               "//a/img")
    img1.click()

    # 35. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 36. Click 'test_editor_02.ipynb1'
    test_editor_02_ipynb1 = driver.find_element(By.XPATH,
                                                "//span[. = 'test_editor_02.ipynb']")
    test_editor_02_ipynb1.click()

    # 37. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 38. Click 'DIV2'
    div2 = driver.find_element(By.XPATH,
                               "//div[6]/div[1]/div/div")
    div2.click()

    # 39. Click 'IMG1'
    img1 = driver.find_element(By.XPATH,
                               "//a/img")
    img1.click()

    # 40. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 41. Click 'test_editor_02.ipynb1'
    test_editor_02_ipynb1 = driver.find_element(By.XPATH,
                                                "//span[. = 'test_editor_02.ipynb']")
    test_editor_02_ipynb1.click()

    # 42. Switch to window '2'
    driver.switch_to.window(driver.window_handles[2])

    # 43. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 44. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 45. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 46. Click 'PRE4'
    pre4 = driver.find_element(By.XPATH,
                               "//div[4]/pre")
    pre4.click()

    # 47. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 48. Click 'IMG1'
    img1 = driver.find_element(By.XPATH,
                               "//a/img")
    img1.click()

    # 49. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 50. Click 'test_editor_02.ipynb1'
    test_editor_02_ipynb1 = driver.find_element(By.XPATH,
                                                "//span[. = 'test_editor_02.ipynb']")
    test_editor_02_ipynb1.click()

    # 51. Switch to window '3'
    driver.switch_to.window(driver.window_handles[3])
