from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: TestProject.Generated.Tests.JupyterNotebookFunctionalTest
    Test: Editor Window - Top Section - Logout
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/05/2021, 12:09:48
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Editor Window - Top Section - Logout")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'test_editor_02.ipynb1'
    test_editor_02_ipynb1 = driver.find_element(By.XPATH,
                                                "//span[. = 'test_editor_02.ipynb']")
    test_editor_02_ipynb1.click()

    # 4. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 5. Click 'Logout'
    logout = driver.find_element(By.CSS_SELECTOR,
                                 "#logout")
    logout.click()

    # 6. Click 'login page'
    login_page = driver.find_element(By.XPATH,
                                     "//a[. = 'login page']")
    login_page.click()

    # 7. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 8. Click 'test_editor_02.ipynb1'
    test_editor_02_ipynb1 = driver.find_element(By.XPATH,
                                                "//span[. = 'test_editor_02.ipynb']")
    test_editor_02_ipynb1.click()

    # 9. Switch to window '3'
    driver.switch_to.window(driver.window_handles[3])

    # 10. Type 'Hello World' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("Hello World")

    # 11. Click 'Logout'
    logout = driver.find_element(By.CSS_SELECTOR,
                                 "#logout")
    logout.click()

    # 12. Click 'ipython-main-app'
    ipython_main_app = driver.find_element(By.CSS_SELECTOR,
                                           "#ipython-main-app")
    ipython_main_app.click()

    # 13. Click 'login page'
    login_page = driver.find_element(By.XPATH,
                                     "//a[. = 'login page']")
    login_page.click()

    # 14. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 15. Click 'test_editor_02.ipynb2'
    test_editor_02_ipynb2 = driver.find_element(By.XPATH,
                                                "//span[. = 'test_editor_02.ipynb']")
    test_editor_02_ipynb2.click()

    # 16. Switch to window '4'
    driver.switch_to.window(driver.window_handles[4])

    # 17. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 18. Click 'Delete CellsD,D'
    delete_cellsd_d = driver.find_element(By.XPATH,
                                          "//a[. = 'Delete CellsD,D']")
    delete_cellsd_d.click()

    # 19. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 20. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 21. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 22. Type 'i += 1' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("i += 1")

    # 23. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 24. Click 'Logout'
    logout = driver.find_element(By.CSS_SELECTOR,
                                 "#logout")
    logout.click()

    # 25. Click 'login page'
    login_page = driver.find_element(By.XPATH,
                                     "//a[. = 'login page']")
    login_page.click()

    # 26. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 27. Click 'test_editor_02.ipynb1'
    test_editor_02_ipynb1 = driver.find_element(By.XPATH,
                                                "//span[. = 'test_editor_02.ipynb']")
    test_editor_02_ipynb1.click()

    # 28. Switch to window '5'
    driver.switch_to.window(driver.window_handles[5])

    # 29. Click 'DIV2'
    div2 = driver.find_element(By.XPATH,
                               "//div[6]/div[1]/div/div")
    div2.click()

    # 30. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 31. Click 'I7'
    i7 = driver.find_element(By.XPATH,
                             "//div[5]/button[2]/i")
    i7.click()
