from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: TestProject.Generated.Tests.JupyterNotebookFunctionalTest
    Test: File Menu - Rename
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/24/2021, 04:32:35
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="File Menu - Rename")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'New'
    new = driver.find_element(By.XPATH,
                              "//span[. = 'New']")
    new.click()

    # 4. Click 'Python 3'
    python_3 = driver.find_element(By.XPATH,
                                   "//a[. = 'Python 3']")
    python_3.click()

    # 5. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 6. Click 'Untitled6'
    untitled6 = driver.find_element(By.CSS_SELECTOR,
                                    "#notebook_name")
    untitled6.click()

    # 7. Type 'test_editor_10' in 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//input")
    input1.send_keys("test_editor_10")

    # 8. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 9. Click 'File'
    file = driver.find_element(By.CSS_SELECTOR,
                               "#filelink")
    file.click()

    # 10. Click 'Rename...'
    rename_ = driver.find_element(By.XPATH,
                                  "//a[. = 'Rename...']")
    rename_.click()

    # 11. Click 'Cancel1'
    cancel1 = driver.find_element(By.XPATH,
                                  "//button[. = 'Cancel']")
    cancel1.click()

    # 12. Click 'File'
    file = driver.find_element(By.CSS_SELECTOR,
                               "#filelink")
    file.click()

    # 13. Click 'Rename...'
    rename_ = driver.find_element(By.XPATH,
                                  "//a[. = 'Rename...']")
    rename_.click()

    # 14. Click 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//input")
    input1.click()

    # 15. Click 'Rename2'
    rename2 = driver.find_element(By.XPATH,
                                  "//button[. = 'Rename']")
    rename2.click()

    # 16. Click 'Cancel1'
    cancel1 = driver.find_element(By.XPATH,
                                  "//button[. = 'Cancel']")
    cancel1.click()

    # 17. Click 'File'
    file = driver.find_element(By.CSS_SELECTOR,
                               "#filelink")
    file.click()

    # 18. Click 'Rename...'
    rename_ = driver.find_element(By.XPATH,
                                  "//a[. = 'Rename...']")
    rename_.click()

    # 19. Click 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//input")
    input1.click()

    # 20. Type 'test_editor_09' in 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//input")
    input1.send_keys("test_editor_09")

    # 21. Click 'Rename2'
    rename2 = driver.find_element(By.XPATH,
                                  "//button[. = 'Rename']")
    rename2.click()

    # 22. Click 'Cancel1'
    cancel1 = driver.find_element(By.XPATH,
                                  "//button[. = 'Cancel']")
    cancel1.click()
