from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: KernelMenuShutdown
    Test: Kernel Menu - Shutdown
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/05/2021, 11:46:55
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Kernel Menu - Shutdown")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'test_editor_02.ipynb1'
    test_editor_02_ipynb1 = driver.find_element(By.XPATH,
                                                "//span[. = 'test_editor_02.ipynb']")
    test_editor_02_ipynb1.click()

    # 4. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 5. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 6. Click 'Shutdown1'
    shutdown1 = driver.find_element(By.XPATH,
                                    "//a[. = 'Shutdown']")
    shutdown1.click()

    # 7. Click 'Shutdown2'
    shutdown2 = driver.find_element(By.XPATH,
                                    "//button[. = 'Shutdown']")
    shutdown2.click()

    # 8. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 9. Click 'Reconnect'
    reconnect = driver.find_element(By.XPATH,
                                    "//a[. = 'Reconnect']")
    reconnect.click()

    # 10. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 11. Click 'Shutdown1'
    shutdown1 = driver.find_element(By.XPATH,
                                    "//a[. = 'Shutdown']")
    shutdown1.click()

    # 12. Click 'Shutdown2'
    shutdown2 = driver.find_element(By.XPATH,
                                    "//button[. = 'Shutdown']")
    shutdown2.click()

    # 13. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 14. Click 'Restart0,0'
    restart0_0 = driver.find_element(By.XPATH,
                                     "//a[. = 'Restart0,0']")
    restart0_0.click()

    # 15. Type 'Hello World' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("Hello World")

    # 16. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 17. Click 'Shutdown1'
    shutdown1 = driver.find_element(By.XPATH,
                                    "//a[. = 'Shutdown']")
    shutdown1.click()

    # 18. Click 'Shutdown2'
    shutdown2 = driver.find_element(By.XPATH,
                                    "//button[. = 'Shutdown']")
    shutdown2.click()

    # 19. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 20. Click 'Run1'
    run1 = driver.find_element(By.XPATH,
                               "//button[. = 'Run']")
    run1.click()

    # 21. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 22. Click 'Shutdown1'
    shutdown1 = driver.find_element(By.XPATH,
                                    "//a[. = 'Shutdown']")
    shutdown1.click()

    # 23. Click 'Shutdown2'
    shutdown2 = driver.find_element(By.XPATH,
                                    "//button[. = 'Shutdown']")
    shutdown2.click()

    # 24. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 25. Click 'Run1'
    run1 = driver.find_element(By.XPATH,
                               "//button[. = 'Run']")
    run1.click()

    # 26. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 27. Click 'Delete CellsD,D'
    delete_cellsd_d = driver.find_element(By.XPATH,
                                          "//a[. = 'Delete CellsD,D']")
    delete_cellsd_d.click()

    # 28. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 29. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 30. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 31. Click 'Delete CellsD,D'
    delete_cellsd_d = driver.find_element(By.XPATH,
                                          "//a[. = 'Delete CellsD,D']")
    delete_cellsd_d.click()

    # 32. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 33. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 34. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 35. Type 'i += 1' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("i += 1")

    # 36. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 37. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 38. Click 'Shutdown1'
    shutdown1 = driver.find_element(By.XPATH,
                                    "//a[. = 'Shutdown']")
    shutdown1.click()

    # 39. Click 'Shutdown2'
    shutdown2 = driver.find_element(By.XPATH,
                                    "//button[. = 'Shutdown']")
    shutdown2.click()

    # 40. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 41. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 42. Type 'Hello World' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("Hello World")

    # 43. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 44. Type '123' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys("123")

    # 45. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 46. Click 'Shutdown1'
    shutdown1 = driver.find_element(By.XPATH,
                                    "//a[. = 'Shutdown']")
    shutdown1.click()

    # 47. Click 'Shutdown2'
    shutdown2 = driver.find_element(By.XPATH,
                                    "//button[. = 'Shutdown']")
    shutdown2.click()

    # 48. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 49. Click 'Run All'
    run_all = driver.find_element(By.XPATH,
                                  "//a[. = 'Run All']")
    run_all.click()

    # 50. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 51. Click 'Shutdown1'
    shutdown1 = driver.find_element(By.XPATH,
                                    "//a[. = 'Shutdown']")
    shutdown1.click()

    # 52. Click 'Shutdown2'
    shutdown2 = driver.find_element(By.XPATH,
                                    "//button[. = 'Shutdown']")
    shutdown2.click()

    # 53. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 54. Click 'Run All'
    run_all = driver.find_element(By.XPATH,
                                  "//a[. = 'Run All']")
    run_all.click()

    # 55. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 56. Click 'Run All'
    run_all = driver.find_element(By.XPATH,
                                  "//a[. = 'Run All']")
    run_all.click()

    # 57. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 58. Click 'Shutdown1'
    shutdown1 = driver.find_element(By.XPATH,
                                    "//a[. = 'Shutdown']")
    shutdown1.click()

    # 59. Click 'Shutdown2'
    shutdown2 = driver.find_element(By.XPATH,
                                    "//button[. = 'Shutdown']")
    shutdown2.click()

    # 60. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 61. Click 'Run All'
    run_all = driver.find_element(By.XPATH,
                                  "//a[. = 'Run All']")
    run_all.click()

    # 62. Click 'Run All'
    run_all = driver.find_element(By.XPATH,
                                  "//a[. = 'Run All']")
    run_all.click()

    # 63. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 64. Click 'Shutdown1'
    shutdown1 = driver.find_element(By.XPATH,
                                    "//a[. = 'Shutdown']")
    shutdown1.click()

    # 65. Click 'Shutdown2'
    shutdown2 = driver.find_element(By.XPATH,
                                    "//button[. = 'Shutdown']")
    shutdown2.click()

    # 66. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 67. Click 'Run All'
    run_all = driver.find_element(By.XPATH,
                                  "//a[. = 'Run All']")
    run_all.click()
