from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: KernelMenuRestart
    Test: Kernel Menu - Interrupt
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/05/2021, 11:45:11
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Kernel Menu - Interrupt")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'test_editor_02.ipynb1'
    test_editor_02_ipynb1 = driver.find_element(By.XPATH,
                                                "//span[. = 'test_editor_02.ipynb']")
    test_editor_02_ipynb1.click()

    # 4. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 5. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 6. Click 'InterruptI,I'
    interrupti_i = driver.find_element(By.XPATH,
                                       "//a[. = 'InterruptI,I']")
    interrupti_i.click()

    # 7. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 8. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 9. Click 'Interrupt'
    interrupt = driver.find_element(By.XPATH,
                                    "//span[. = 'Interrupt']")
    interrupt.click()

    # 10. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 11. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 12. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 13. Click 'PRE3'
    pre3 = driver.find_element(By.XPATH,
                               "//div[5]/div[1]/pre")
    pre3.click()

    # 14. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 15. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 16. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 17. Click 'Interrupt'
    interrupt = driver.find_element(By.XPATH,
                                    "//span[. = 'Interrupt']")
    interrupt.click()

    # 18. Click 'I7'
    i7 = driver.find_element(By.XPATH,
                             "//div[5]/button[2]/i")
    i7.click()

    # 19. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 20. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()
