from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: KernelMenuReconnect
    Test: Kernel Menu - Reconnect
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/05/2021, 11:46:22
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Kernel Menu - Reconnect")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'test_editor_02.ipynb1'
    test_editor_02_ipynb1 = driver.find_element(By.XPATH,
                                                "//span[. = 'test_editor_02.ipynb']")
    test_editor_02_ipynb1.click()

    # 4. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 5. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 6. Click 'Reconnect'
    reconnect = driver.find_element(By.XPATH,
                                    "//a[. = 'Reconnect']")
    reconnect.click()

    # 7. Type 'Hello World' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("Hello World")

    # 8. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 9. Click 'Reconnect'
    reconnect = driver.find_element(By.XPATH,
                                    "//a[. = 'Reconnect']")
    reconnect.click()

    # 10. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 11. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 12. Click 'Reconnect'
    reconnect = driver.find_element(By.XPATH,
                                    "//a[. = 'Reconnect']")
    reconnect.click()

    # 13. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 14. Click 'Delete CellsD,D'
    delete_cellsd_d = driver.find_element(By.XPATH,
                                          "//a[. = 'Delete CellsD,D']")
    delete_cellsd_d.click()

    # 15. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 16. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 17. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 18. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 19. Type 'er a number: ' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("er a number: ")

    # 20. Click 'Run'
    run = driver.find_element(By.XPATH,
                              "//span[. = 'Run']")
    run.click()

    # 21. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 22. Click 'Reconnect'
    reconnect = driver.find_element(By.XPATH,
                                    "//a[. = 'Reconnect']")
    reconnect.click()

    # 23. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 24. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 25. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 26. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 27. Click 'DIV2'
    div2 = driver.find_element(By.XPATH,
                               "//div[6]/div[1]/div/div")
    div2.click()

    # 28. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 29. Type '123' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys("123")

    # 30. Click 'Reconnect'
    reconnect = driver.find_element(By.XPATH,
                                    "//a[. = 'Reconnect']")
    reconnect.click()

    # 31. Click 'Run All'
    run_all = driver.find_element(By.XPATH,
                                  "//a[. = 'Run All']")
    run_all.click()

    # 32. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 33. Click 'Reconnect'
    reconnect = driver.find_element(By.XPATH,
                                    "//a[. = 'Reconnect']")
    reconnect.click()

    # 34. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 35. Click 'Run All'
    run_all = driver.find_element(By.XPATH,
                                  "//a[. = 'Run All']")
    run_all.click()

    # 36. Type 'Enter a number: ' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys("Enter a number: ")

    # 37. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 38. Click 'Run All'
    run_all = driver.find_element(By.XPATH,
                                  "//a[. = 'Run All']")
    run_all.click()

    # 39. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 40. Click 'Reconnect'
    reconnect = driver.find_element(By.XPATH,
                                    "//a[. = 'Reconnect']")
    reconnect.click()

    # 41. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 42. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 43. Click 'Run All'
    run_all = driver.find_element(By.XPATH,
                                  "//a[. = 'Run All']")
    run_all.click()

    # 44. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 45. Click 'Run All'
    run_all = driver.find_element(By.XPATH,
                                  "//a[. = 'Run All']")
    run_all.click()
