from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: KernelMenuRestart
    Test: Kernel Menu - Restart
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/05/2021, 11:45:53
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Kernel Menu - Restart")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'test_editor_02.ipynb1'
    test_editor_02_ipynb1 = driver.find_element(By.XPATH,
                                                "//span[. = 'test_editor_02.ipynb']")
    test_editor_02_ipynb1.click()

    # 4. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 5. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 6. Click 'Restart0,0'
    restart0_0 = driver.find_element(By.XPATH,
                                     "//a[. = 'Restart0,0']")
    restart0_0.click()

    # 7. Click 'Restart'
    restart = driver.find_element(By.XPATH,
                                  "//button[. = 'Restart']")
    restart.click()

    # 8. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 9. Type 'Enter a number: ' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys("Enter a number: ")

    # 10. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 11. Click 'Restart1'
    restart1 = driver.find_element(By.XPATH,
                                   "//span[. = 'Restart']")
    restart1.click()

    # 12. Click 'Restart2'
    restart2 = driver.find_element(By.XPATH,
                                   "//button[. = 'Restart']")
    restart2.click()

    # 13. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 14. Click 'Run All'
    run_all = driver.find_element(By.XPATH,
                                  "//a[. = 'Run All']")
    run_all.click()

    # 15. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 16. Click 'Restart0,0'
    restart0_0 = driver.find_element(By.XPATH,
                                     "//a[. = 'Restart0,0']")
    restart0_0.click()

    # 17. Click 'Restart2'
    restart2 = driver.find_element(By.XPATH,
                                   "//button[. = 'Restart']")
    restart2.click()

    # 18. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 19. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 20. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 21. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 22. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 23. Click 'Restart & Clear Output'
    restart_clear_output = driver.find_element(By.XPATH,
                                               "//a[. = 'Restart & Clear Output']")
    restart_clear_output.click()

    # 24. Click 'Restart and Clear All Outputs'
    restart_and_clear_all_outputs = driver.find_element(By.XPATH,
                                                        "//button[. = 'Restart and Clear All Outputs']")
    restart_and_clear_all_outputs.click()

    # 25. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 26. Type 'Enter a number: ' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys("Enter a number: ")

    # 27. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 28. Click 'Restart & Clear Output'
    restart_clear_output = driver.find_element(By.XPATH,
                                               "//a[. = 'Restart & Clear Output']")
    restart_clear_output.click()

    # 29. Click 'Restart and Clear All Outputs'
    restart_and_clear_all_outputs = driver.find_element(By.XPATH,
                                                        "//button[. = 'Restart and Clear All Outputs']")
    restart_and_clear_all_outputs.click()

    # 30. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 31. Click 'Run All'
    run_all = driver.find_element(By.XPATH,
                                  "//a[. = 'Run All']")
    run_all.click()

    # 32. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 33. Click 'Restart & Clear Output'
    restart_clear_output = driver.find_element(By.XPATH,
                                               "//a[. = 'Restart & Clear Output']")
    restart_clear_output.click()

    # 34. Click 'Restart and Clear All Outputs'
    restart_and_clear_all_outputs = driver.find_element(By.XPATH,
                                                        "//button[. = 'Restart and Clear All Outputs']")
    restart_and_clear_all_outputs.click()

    # 35. Click 'DIV3'
    div3 = driver.find_element(By.XPATH,
                               "//div[2]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div")
    div3.click()

    # 36. Type '[NONE]' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys("")

    # 37. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 38. Click 'Run All'
    run_all = driver.find_element(By.XPATH,
                                  "//a[. = 'Run All']")
    run_all.click()

    # 39. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 40. Click 'Restart0,0'
    restart0_0 = driver.find_element(By.XPATH,
                                     "//a[. = 'Restart0,0']")
    restart0_0.click()

    # 41. Click 'Restart2'
    restart2 = driver.find_element(By.XPATH,
                                   "//button[. = 'Restart']")
    restart2.click()

    # 42. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 43. Click 'Restart & Clear Output'
    restart_clear_output = driver.find_element(By.XPATH,
                                               "//a[. = 'Restart & Clear Output']")
    restart_clear_output.click()

    # 44. Click 'Restart and Clear All Outputs'
    restart_and_clear_all_outputs = driver.find_element(By.XPATH,
                                                        "//button[. = 'Restart and Clear All Outputs']")
    restart_and_clear_all_outputs.click()

    # 45. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 46. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 47. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 48. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 49. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 50. Click 'Restart & Run All'
    restart_run_all = driver.find_element(By.XPATH,
                                          "//a[. = 'Restart & Run All']")
    restart_run_all.click()

    # 51. Click 'Restart and Run All Cells'
    restart_and_run_all_cells = driver.find_element(By.XPATH,
                                                    "//button[. = 'Restart and Run All Cells']")
    restart_and_run_all_cells.click()

    # 52. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 53. Type '123' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys("123")

    # 54. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 55. Click 'Restart & Run All'
    restart_run_all = driver.find_element(By.XPATH,
                                          "//a[. = 'Restart & Run All']")
    restart_run_all.click()

    # 56. Click 'Restart and Run All Cells'
    restart_and_run_all_cells = driver.find_element(By.XPATH,
                                                    "//button[. = 'Restart and Run All Cells']")
    restart_and_run_all_cells.click()

    # 57. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 58. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 59. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 60. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 61. Type 'Hello World' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("Hello World")

    # 62. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 63. Click 'Restart & Run All'
    restart_run_all = driver.find_element(By.XPATH,
                                          "//a[. = 'Restart & Run All']")
    restart_run_all.click()

    # 64. Click 'Restart and Run All Cells'
    restart_and_run_all_cells = driver.find_element(By.XPATH,
                                                    "//button[. = 'Restart and Run All Cells']")
    restart_and_run_all_cells.click()

    # 65. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 66. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 67. Type 'Enter a number: ' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("Enter a number: ")

    # 68. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 69. Click 'Restart & Run All'
    restart_run_all = driver.find_element(By.XPATH,
                                          "//a[. = 'Restart & Run All']")
    restart_run_all.click()

    # 70. Click 'Restart and Run All Cells'
    restart_and_run_all_cells = driver.find_element(By.XPATH,
                                                    "//button[. = 'Restart and Run All Cells']")
    restart_and_run_all_cells.click()

    # 71. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 72. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 73. Click 'DIV2'
    div2 = driver.find_element(By.XPATH,
                               "//div[6]/div[1]/div/div")
    div2.click()

    # 74. Type 'Hello World' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("Hello World")

    # 75. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 76. Click 'insert cell below'
    insert_cell_below = driver.find_element(By.XPATH,
                                            "//div[2]/button")
    insert_cell_below.click()

    # 77. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 78. Click 'Restart & Run All'
    restart_run_all = driver.find_element(By.XPATH,
                                          "//a[. = 'Restart & Run All']")
    restart_run_all.click()

    # 79. Click 'Restart and Run All Cells1'
    restart_and_run_all_cells1 = driver.find_element(By.XPATH,
                                                     "//button[. = 'Restart and Run All Cells']")
    restart_and_run_all_cells1.click()

    # 80. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 81. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 82. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 83. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 84. Type 'Hello World' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("Hello World")

    # 85. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 86. Type '123' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys("123")

    # 87. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 88. Click 'Run All'
    run_all = driver.find_element(By.XPATH,
                                  "//a[. = 'Run All']")
    run_all.click()

    # 89. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 90. Click 'Restart & Run All'
    restart_run_all = driver.find_element(By.XPATH,
                                          "//a[. = 'Restart & Run All']")
    restart_run_all.click()

    # 91. Click 'Restart and Run All Cells1'
    restart_and_run_all_cells1 = driver.find_element(By.XPATH,
                                                     "//button[. = 'Restart and Run All Cells']")
    restart_and_run_all_cells1.click()

    # 92. Type 'Enter a number: ' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys("Enter a number: ")

    # 93. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 94. Click 'Run All'
    run_all = driver.find_element(By.XPATH,
                                  "//a[. = 'Run All']")
    run_all.click()

    # 95. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 96. Click 'Restart & Run All'
    restart_run_all = driver.find_element(By.XPATH,
                                          "//a[. = 'Restart & Run All']")
    restart_run_all.click()

    # 97. Click 'Restart and Run All Cells1'
    restart_and_run_all_cells1 = driver.find_element(By.XPATH,
                                                     "//button[. = 'Restart and Run All Cells']")
    restart_and_run_all_cells1.click()

    # 98. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 99. Click 'Kernel'
    kernel = driver.find_element(By.CSS_SELECTOR,
                                 "#kernellink")
    kernel.click()

    # 100. Click 'Restart & Run All'
    restart_run_all = driver.find_element(By.XPATH,
                                          "//a[. = 'Restart & Run All']")
    restart_run_all.click()

    # 101. Click 'Restart and Run All Cells1'
    restart_and_run_all_cells1 = driver.find_element(By.XPATH,
                                                     "//button[. = 'Restart and Run All Cells']")
    restart_and_run_all_cells1.click()
