from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: CreateFolder
    Test: Create Folder
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 04/24/2021, 14:01:05
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Create Folder")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://127.0.0.1:8888/?token=4636fe43668233d67fde93f4eef1a508ae550c7c29be077c"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'HTML'
    html = driver.find_element(By.XPATH,
                               "/html")
    html.click()

    # 3. Click 'Folder'
    folder = driver.find_element(By.XPATH,
                                 "//a[. = 'Folder']")
    folder.click()

    # 4. Click 'Click here to rename, delete, etc.'
    click_here_to_rename_delete_etc_ = driver.find_element(By.XPATH,
                                                           "//div[22]//input")
    click_here_to_rename_delete_etc_.click()

    # 5. Click 'Rename'
    rename = driver.find_element(By.XPATH,
                                 "//button[. = 'Rename']")
    rename.click()

    # 6. Click 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//div[4]/div/div//input")
    input.click()

    # 7. Type 'functional test folder' in 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//div[4]/div/div//input")
    input.send_keys("functional test folder")

    # 8. Click 'Rename1'
    rename1 = driver.find_element(By.XPATH,
                                  "//div[3]/button[. = 'Rename']")
    rename1.click()

    # 9. Click 'OK'
    ok = driver.find_element(By.XPATH,
                             "//button[. = 'OK']")
    ok.click()
