from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: CreateFiles
    Test: Create Files
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 04/27/2021, 06:41:59
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Create Files")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'New
    #
    #               ...'
    new_ = driver.find_element(By.CSS_SELECTOR,
                               "#new-dropdown-button")
    new_.click()

    # 3. Click 'Python 3'
    python_3 = driver.find_element(By.XPATH,
                                   "//a[. = 'Python 3']")
    python_3.click()

    # 4. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 5. Click 'Untitled6'
    untitled6 = driver.find_element(By.CSS_SELECTOR,
                                    "#notebook_name")
    untitled6.click()

    # 6. Type 'test_create_pyfile' in 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//input")
    input1.send_keys("test_create_pyfile")

    # 7. Click 'Rename2'
    rename2 = driver.find_element(By.XPATH,
                                  "//button[. = 'Rename']")
    rename2.click()

    # 8. Switch to window '0'
    driver.switch_to.window(driver.window_handles[0])

    # 9. Click 'New
    #
    #               ...'
    new_ = driver.find_element(By.CSS_SELECTOR,
                               "#new-dropdown-button")
    new_.click()

    # 10. Click 'Text File'
    text_file = driver.find_element(By.XPATH,
                                    "//a[. = 'Text File']")
    text_file.click()

    # 11. Switch to window '2'
    driver.switch_to.window(driver.window_handles[2])

    # 12. Click 'DIV'
    div = driver.find_element(By.XPATH,
                              "//div[6]")
    div.click()

    # 13. Click 'untitled.txt'
    untitled_txt = driver.find_element(By.XPATH,
                                       "//span[. = 'untitled.txt']")
    untitled_txt.click()

    # 14. Click 'INPUT2'
    input2 = driver.find_element(By.XPATH,
                                 "//input")
    input2.click()

    # 15. Click 'DIV1'
    div1 = driver.find_element(By.XPATH,
                               "//body/div[4]")
    div1.click()

    # 16. Type 'test_create_txtfile.txt' in 'INPUT2'
    input2 = driver.find_element(By.XPATH,
                                 "//input")
    input2.send_keys("test_create_txtfile.txt")

    # 17. Click 'OK1'
    ok1 = driver.find_element(By.XPATH,
                              "//button[. = 'OK']")
    ok1.click()

    # 18. Switch to window '0'
    driver.switch_to.window(driver.window_handles[0])

    # 19. Click 'SPAN'
    span = driver.find_element(By.XPATH,
                               "//div/div/div/div/div[1]/div[1]/div[2]/div/div[1]/button/span[2]")
    span.click()

    # 20. Click 'Terminal'
    terminal = driver.find_element(By.XPATH,
                                   "//a[. = 'Terminal']")
    terminal.click()

    # 21. Switch to window '3'
    driver.switch_to.window(driver.window_handles[3])

    # 22. Switch to window '0'
    driver.switch_to.window(driver.window_handles[0])
