from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: BasicBrowsingBehaviors
    Test: Basic Browsing Behaviors
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 04/24/2021, 14:03:27
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Basic Browsing Behaviors")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://127.0.0.1:8888/?token=4636fe43668233d67fde93f4eef1a508ae550c7c29be077c"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'I'
    i = driver.find_element(By.XPATH,
                            "//div[2]/ul//i")
    i.click()

    # 4. Click 'Documents'
    documents = driver.find_element(By.XPATH,
                                    "//span[. = 'Documents']")
    documents.click()

    # 5. Click 'I.T'
    i_t = driver.find_element(By.XPATH,
                              "//span[. = 'I.T']")
    i_t.click()

    # 6. Click 'testfolder'
    testfolder = driver.find_element(By.XPATH,
                                     "//span[. = 'testfolder']")
    testfolder.click()

    # 7. Click 'I'
    i = driver.find_element(By.XPATH,
                            "//div[2]/ul//i")
    i.click()

    # 8. Click 'I1'
    i1 = driver.find_element(By.XPATH,
                             "//div[2]/div/div[2]/button/i")
    i1.click()

    # 9. Click 'I2'
    i2 = driver.find_element(By.XPATH,
                             "//div[1]/button/i")
    i2.click()

    # 10. Click 'Name'
    name = driver.find_element(By.CSS_SELECTOR,
                               "#sort-name")
    name.click()

    # 11. Click 'I2'
    i2 = driver.find_element(By.XPATH,
                             "//div[1]/button/i")
    i2.click()

    # 12. Click 'Name'
    name = driver.find_element(By.CSS_SELECTOR,
                               "#sort-name")
    name.click()

    # 13. Click 'Last Modified'
    last_modified = driver.find_element(By.CSS_SELECTOR,
                                        "#last-modified")
    last_modified.click()

    # 14. Click 'Last Modified'
    last_modified = driver.find_element(By.CSS_SELECTOR,
                                        "#last-modified")
    last_modified.click()

    # 15. Click 'File size'
    file_size = driver.find_element(By.CSS_SELECTOR,
                                    "#file-size")
    file_size.click()

    # 16. Click 'File size'
    file_size = driver.find_element(By.CSS_SELECTOR,
                                    "#file-size")
    file_size.click()

    # 17. Click 'Name'
    name = driver.find_element(By.CSS_SELECTOR,
                               "#sort-name")
    name.click()

    # 18. Click 'Running'
    running = driver.find_element(By.XPATH,
                                  "//a[. = 'Running']")
    running.click()

    # 19. Click 'Clusters'
    clusters = driver.find_element(By.XPATH,
                                   "//a[. = 'Clusters']")
    clusters.click()

    # 20. Click 'Clusters'
    clusters = driver.find_element(By.XPATH,
                                   "//a[. = 'Clusters']")
    clusters.click()

    # 21. Click 'Running'
    running = driver.find_element(By.XPATH,
                                  "//a[. = 'Running']")
    running.click()

    # 22. Click 'Files'
    files = driver.find_element(By.XPATH,
                                "//a[. = 'Files']")
    files.click()
