from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: BatchOperationsMultipleSelection
    Test: Batch Operations - Multiple Selection
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 04/24/2021, 14:04:55
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Batch Operations - Multiple Selection")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://127.0.0.1:8888/?token=4636fe43668233d67fde93f4eef1a508ae550c7c29be077c"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'SPAN1'
    span1 = driver.find_element(By.XPATH,
                                "//body/div[1]//span[1]")
    span1.click()

    # 3. Click 'checkbox
    #
    #          ...'
    checkbox_ = driver.find_element(By.CSS_SELECTOR,
                                    "#tree-selector-btn")
    checkbox_.click()

    # 4. Click 'Folders'
    folders = driver.find_element(By.CSS_SELECTOR,
                                  "#select-folders")
    folders.click()

    # 5. Click 'SPAN2'
    span2 = driver.find_element(By.XPATH,
                                "//button[2]/span[2]")
    span2.click()

    # 6. Click 'All Notebooks'
    all_notebooks = driver.find_element(By.CSS_SELECTOR,
                                        "#select-notebooks")
    all_notebooks.click()

    # 7. Click 'checkbox
    #
    #          ...'
    checkbox_ = driver.find_element(By.CSS_SELECTOR,
                                    "#tree-selector-btn")
    checkbox_.click()

    # 8. Click 'Running1'
    running1 = driver.find_element(By.CSS_SELECTOR,
                                   "#select-running-notebooks")
    running1.click()

    # 9. Click 'checkbox
    #
    #          ...'
    checkbox_ = driver.find_element(By.CSS_SELECTOR,
                                    "#tree-selector-btn")
    checkbox_.click()

    # 10. Click 'Files1'
    files1 = driver.find_element(By.CSS_SELECTOR,
                                 "#select-files")
    files1.click()

    # 11. Click 'checkbox
    #
    #          ...'
    checkbox_ = driver.find_element(By.CSS_SELECTOR,
                                    "#tree-selector-btn")
    checkbox_.click()

    # 12. Click 'select-all'
    select_all = driver.find_element(By.CSS_SELECTOR,
                                     "#select-all")
    select_all.click()

    # 13. Click 'select-all'
    select_all = driver.find_element(By.CSS_SELECTOR,
                                     "#select-all")
    select_all.click()
