from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: TestProject.Generated.Tests.JupyterNotebookFunctionalTest
    Test: Cell Menu - Toolbar
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/24/2021, 04:30:41
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Cell Menu - Toolbar")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'test_editor_10.ipynb'
    test_editor_10_ipynb = driver.find_element(By.XPATH,
                                               "//span[. = 'test_editor_10.ipynb']")
    test_editor_10_ipynb.click()

    # 4. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 5. Click 'I11'
    i11 = driver.find_element(By.XPATH,
                              "//div[6]//i")
    i11.click()

    # 6. Click 'change cell to heading 6  6'
    change_cell_to_heading_6_6 = driver.find_element(By.XPATH,
                                                     "//div[11]//a[. = 'change cell to heading 6  6']")
    change_cell_to_heading_6_6.click()

    # 7. Click 'I11'
    i11 = driver.find_element(By.XPATH,
                              "//div[6]//i")
    i11.click()

    # 8. Click 'change cell to code  Y'
    change_cell_to_code_y = driver.find_element(By.XPATH,
                                                "//div[12]//a[. = 'change cell to code  Y']")
    change_cell_to_code_y.click()

    # 9. Type 'Hello World' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("Hello World")

    # 10. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 11. Type '123' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys("123")

    # 12. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 13. Click 'Run All'
    run_all = driver.find_element(By.XPATH,
                                  "//a[. = 'Run All']")
    run_all.click()

    # 14. Click 'I11'
    i11 = driver.find_element(By.XPATH,
                              "//div[6]//i")
    i11.click()

    # 15. Click 'restart kernel and clear output'
    restart_kernel_and_clear_output = driver.find_element(By.XPATH,
                                                          "//div[13]//a[. = 'restart kernel and clear output  ']")
    restart_kernel_and_clear_output.click()

    # 16. Click 'I11'
    i11 = driver.find_element(By.XPATH,
                              "//div[6]//i")
    i11.click()

    # 17. Click 'extend selection below  ⇧J'
    extend_selection_below_j = driver.find_element(By.XPATH,
                                                   "//div[14]//a[. = 'extend selection below  ⇧J']")
    extend_selection_below_j.click()

    # 18. Click 'open the command palette'
    open_the_command_palette = driver.find_element(By.XPATH,
                                                   "//div[6]/button")
    open_the_command_palette.click()

    # 19. Click 'insert cell above  A'
    insert_cell_above_a = driver.find_element(By.XPATH,
                                              "//div[15]//a[. = 'insert cell above  A']")
    insert_cell_above_a.click()

    # 20. Click 'I11'
    i11 = driver.find_element(By.XPATH,
                              "//div[6]//i")
    i11.click()

    # 21. Click 'embed interactive widgets'
    embed_interactive_widgets = driver.find_element(By.XPATH,
                                                    "//div[16]//a[. = 'embed interactive widgets  ']")
    embed_interactive_widgets.click()

    # 22. Click 'Copy to Clipboard1'
    copy_to_clipboard1 = driver.find_element(By.XPATH,
                                             "//button[. = 'Copy to Clipboard']")
    copy_to_clipboard1.click()

    # 23. Click 'I11'
    i11 = driver.find_element(By.XPATH,
                              "//div[6]//i")
    i11.click()

    # 24. Click 'save with widgets'
    save_with_widgets = driver.find_element(By.XPATH,
                                            "//div[17]//a[. = 'save with widgets  ']")
    save_with_widgets.click()
