from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: CellMenuRunAllBelow
    Test: Cell Menu - Run All Below
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/01/2021, 02:05:02
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Cell Menu - Run All Below")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'test_editor_02.ipynb'
    test_editor_02_ipynb = driver.find_element(By.XPATH,
                                               "//span[. = 'test_editor_02.ipynb']")
    test_editor_02_ipynb.click()

    # 4. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 5. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 6. Click 'Run All Below'
    run_all_below = driver.find_element(By.XPATH,
                                        "//a[. = 'Run All Below']")
    run_all_below.click()

    # 7. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 8. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 9. Click 'Run All Below'
    run_all_below = driver.find_element(By.XPATH,
                                        "//a[. = 'Run All Below']")
    run_all_below.click()

    # 10. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 11. Click 'Run All Below'
    run_all_below = driver.find_element(By.XPATH,
                                        "//a[. = 'Run All Below']")
    run_all_below.click()

    # 12. Type 'Hello World' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys("Hello World")

    # 13. Click 'menubar-container'
    menubar_container = driver.find_element(By.CSS_SELECTOR,
                                            "#menubar-container")
    menubar_container.click()

    # 14. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 15. Click 'Run All Below'
    run_all_below = driver.find_element(By.XPATH,
                                        "//a[. = 'Run All Below']")
    run_all_below.click()

    # 16. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 17. Click 'Run All Below'
    run_all_below = driver.find_element(By.XPATH,
                                        "//a[. = 'Run All Below']")
    run_all_below.click()

    # 18. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 19. Type '123' in 'TEXTAREA5'
    textarea5 = driver.find_element(By.XPATH,
                                    "//div[3]//textarea")
    textarea5.send_keys("123")

    # 20. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 21. Click 'Run All Below'
    run_all_below = driver.find_element(By.XPATH,
                                        "//a[. = 'Run All Below']")
    run_all_below.click()

    # 22. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 23. Click 'Delete CellsD,D'
    delete_cellsd_d = driver.find_element(By.XPATH,
                                          "//a[. = 'Delete CellsD,D']")
    delete_cellsd_d.click()

    # 24. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 25. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 26. Click 'insert cell below'
    insert_cell_below = driver.find_element(By.XPATH,
                                            "//div[2]/button")
    insert_cell_below.click()

    # 27. Type 'Hello World' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys("Hello World")

    # 28. Click 'insert cell below'
    insert_cell_below = driver.find_element(By.XPATH,
                                            "//div[2]/button")
    insert_cell_below.click()

    # 29. Type '123' in 'TEXTAREA5'
    textarea5 = driver.find_element(By.XPATH,
                                    "//div[3]//textarea")
    textarea5.send_keys("123")

    # 30. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 31. Click 'Run All Below'
    run_all_below = driver.find_element(By.XPATH,
                                        "//a[. = 'Run All Below']")
    run_all_below.click()

    # 32. Type 'Hello' in 'TEXTAREA5'
    textarea5 = driver.find_element(By.XPATH,
                                    "//div[3]//textarea")
    textarea5.send_keys("Hello")

    # 33. Click 'DIV4'
    div4 = driver.find_element(By.XPATH,
                               "//div[1]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div")
    div4.click()

    # 34. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 35. Click 'Run All Below'
    run_all_below = driver.find_element(By.XPATH,
                                        "//a[. = 'Run All Below']")
    run_all_below.click()

    # 36. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 37. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 38. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 39. Click 'Delete CellsD,D'
    delete_cellsd_d = driver.find_element(By.XPATH,
                                          "//a[. = 'Delete CellsD,D']")
    delete_cellsd_d.click()

    # 40. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 41. Click 'insert cell below'
    insert_cell_below = driver.find_element(By.XPATH,
                                            "//div[2]/button")
    insert_cell_below.click()

    # 42. Type 'Hello' in 'TEXTAREA5'
    textarea5 = driver.find_element(By.XPATH,
                                    "//div[3]//textarea")
    textarea5.send_keys("Hello")

    # 43. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 44. Click 'Run All Below'
    run_all_below = driver.find_element(By.XPATH,
                                        "//a[. = 'Run All Below']")
    run_all_below.click()

    # 45. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 46. Click 'Delete CellsD,D'
    delete_cellsd_d = driver.find_element(By.XPATH,
                                          "//a[. = 'Delete CellsD,D']")
    delete_cellsd_d.click()

    # 47. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 48. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 49. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 50. Type 'Hello' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys("Hello")

    # 51. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 52. Type 'Hello World' in 'TEXTAREA5'
    textarea5 = driver.find_element(By.XPATH,
                                    "//div[3]//textarea")
    textarea5.send_keys("Hello World")

    # 53. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 54. Click 'Run All Below'
    run_all_below = driver.find_element(By.XPATH,
                                        "//a[. = 'Run All Below']")
    run_all_below.click()

    # 55. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 56. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 57. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 58. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 59. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 60. Type 'Hello' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys("Hello")

    # 61. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 62. Type 'Hello World' in 'TEXTAREA5'
    textarea5 = driver.find_element(By.XPATH,
                                    "//div[3]//textarea")
    textarea5.send_keys("Hello World")

    # 63. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 64. Click 'Run All Below'
    run_all_below = driver.find_element(By.XPATH,
                                        "//a[. = 'Run All Below']")
    run_all_below.click()

    # 65. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 66. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 67. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 68. Click 'Delete CellsD,D'
    delete_cellsd_d = driver.find_element(By.XPATH,
                                          "//a[. = 'Delete CellsD,D']")
    delete_cellsd_d.click()

    # 69. Click 'insert cell below'
    insert_cell_below = driver.find_element(By.XPATH,
                                            "//div[2]/button")
    insert_cell_below.click()

    # 70. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 71. Type '10' in 'TEXTAREA5'
    textarea5 = driver.find_element(By.XPATH,
                                    "//div[3]//textarea")
    textarea5.send_keys("10")

    # 72. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 73. Click 'Run All Below'
    run_all_below = driver.find_element(By.XPATH,
                                        "//a[. = 'Run All Below']")
    run_all_below.click()

    # 74. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 75. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 76. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 77. Click 'Delete CellsD,D'
    delete_cellsd_d = driver.find_element(By.XPATH,
                                          "//a[. = 'Delete CellsD,D']")
    delete_cellsd_d.click()

    # 78. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 79. Type 'Hello' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys("Hello")

    # 80. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 81. Click 'DIV8'
    div8 = driver.find_element(By.XPATH,
                               "//div[3]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div")
    div8.click()

    # 82. Type '10' in 'TEXTAREA5'
    textarea5 = driver.find_element(By.XPATH,
                                    "//div[3]//textarea")
    textarea5.send_keys("10")

    # 83. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 84. Click 'Run All Below'
    run_all_below = driver.find_element(By.XPATH,
                                        "//a[. = 'Run All Below']")
    run_all_below.click()
