from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: CellMenuRunSingleCell
    Test: Cell Menu - Run Single Cell
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/01/2021, 02:03:26
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Cell Menu - Run Single Cell")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'test_editor_02.ipynb'
    test_editor_02_ipynb = driver.find_element(By.XPATH,
                                               "//span[. = 'test_editor_02.ipynb']")
    test_editor_02_ipynb.click()

    # 4. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 5. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 6. Click 'Run Cells'
    run_cells = driver.find_element(By.XPATH,
                                    "//span[. = 'Run Cells']")
    run_cells.click()

    # 7. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 8. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 9. Click 'Run Cells'
    run_cells = driver.find_element(By.XPATH,
                                    "//span[. = 'Run Cells']")
    run_cells.click()

    # 10. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 11. Click 'Run Cells'
    run_cells = driver.find_element(By.XPATH,
                                    "//span[. = 'Run Cells']")
    run_cells.click()

    # 12. Click 'PRE'
    pre = driver.find_element(By.XPATH,
                              "//div[1]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div/div/div[5]//pre")
    pre.click()

    # 13. Type '[NONE]' in 'TEXTAREA2'
    textarea2 = driver.find_element(By.XPATH,
                                    "//div[1]/div[1]/div[2]/div[2]//textarea")
    textarea2.send_keys("")

    # 14. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 15. Click 'Run Cells'
    run_cells = driver.find_element(By.XPATH,
                                    "//span[. = 'Run Cells']")
    run_cells.click()

    # 16. Click 'DIV4'
    div4 = driver.find_element(By.XPATH,
                               "//div[1]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div")
    div4.click()

    # 17. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 18. Click 'Run Cells'
    run_cells = driver.find_element(By.XPATH,
                                    "//span[. = 'Run Cells']")
    run_cells.click()

    # 19. Click 'DIV4'
    div4 = driver.find_element(By.XPATH,
                               "//div[1]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div")
    div4.click()

    # 20. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 21. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 22. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 23. Click 'PRE1'
    pre1 = driver.find_element(By.XPATH,
                               "//div[5]/div[3]/pre")
    pre1.click()

    # 24. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 25. Click 'Run Cells'
    run_cells = driver.find_element(By.XPATH,
                                    "//span[. = 'Run Cells']")
    run_cells.click()

    # 26. Click 'PRE1'
    pre1 = driver.find_element(By.XPATH,
                               "//div[5]/div[3]/pre")
    pre1.click()

    # 27. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 28. Click 'Run Cells'
    run_cells = driver.find_element(By.XPATH,
                                    "//span[. = 'Run Cells']")
    run_cells.click()

    # 29. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 30. Click 'Run Cells⌃↩'
    run_cells_ = driver.find_element(By.XPATH,
                                     "//a[. = 'Run Cells⌃↩']")
    run_cells_.click()

    # 31. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 32. Click 'Run Cells'
    run_cells = driver.find_element(By.XPATH,
                                    "//span[. = 'Run Cells']")
    run_cells.click()

    # 33. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 34. Click 'Run Cells and Select Below'
    run_cells_and_select_below = driver.find_element(By.XPATH,
                                                     "//span[. = 'Run Cells and Select Below']")
    run_cells_and_select_below.click()

    # 35. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 36. Click 'Run Cells and Select Below'
    run_cells_and_select_below = driver.find_element(By.XPATH,
                                                     "//span[. = 'Run Cells and Select Below']")
    run_cells_and_select_below.click()

    # 37. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 38. Click 'Delete CellsD,D'
    delete_cellsd_d = driver.find_element(By.XPATH,
                                          "//a[. = 'Delete CellsD,D']")
    delete_cellsd_d.click()

    # 39. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 40. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 41. Type 'Hello World' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("Hello World")

    # 42. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 43. Click 'Run Cells and Select Below'
    run_cells_and_select_below = driver.find_element(By.XPATH,
                                                     "//span[. = 'Run Cells and Select Below']")
    run_cells_and_select_below.click()

    # 44. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 45. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 46. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 47. Click 'Run Cells and Select Below'
    run_cells_and_select_below = driver.find_element(By.XPATH,
                                                     "//span[. = 'Run Cells and Select Below']")
    run_cells_and_select_below.click()

    # 48. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 49. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 50. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 51. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 52. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 53. Click 'Delete Cells'
    delete_cells = driver.find_element(By.XPATH,
                                       "//span[. = 'Delete Cells']")
    delete_cells.click()

    # 54. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 55. Click 'Run Cells and Insert Below'
    run_cells_and_insert_below = driver.find_element(By.XPATH,
                                                     "//span[. = 'Run Cells and Insert Below']")
    run_cells_and_insert_below.click()

    # 56. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 57. Click 'Run Cells and Insert Below'
    run_cells_and_insert_below = driver.find_element(By.XPATH,
                                                     "//span[. = 'Run Cells and Insert Below']")
    run_cells_and_insert_below.click()

    # 58. Type 'World' in 'TEXTAREA5'
    textarea5 = driver.find_element(By.XPATH,
                                    "//div[3]//textarea")
    textarea5.send_keys("World")

    # 59. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 60. Click 'Run Cells and Insert Below'
    run_cells_and_insert_below = driver.find_element(By.XPATH,
                                                     "//span[. = 'Run Cells and Insert Below']")
    run_cells_and_insert_below.click()

    # 61. Type 'Hello' in 'TEXTAREA6'
    textarea6 = driver.find_element(By.XPATH,
                                    "//div[4]/div[1]/div[2]//textarea")
    textarea6.send_keys("Hello")

    # 62. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 63. Click 'Run Cells and Insert Below'
    run_cells_and_insert_below = driver.find_element(By.XPATH,
                                                     "//span[. = 'Run Cells and Insert Below']")
    run_cells_and_insert_below.click()
