from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: CellMenuAllOutput
    Test: Cell menu - All Output
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/05/2021, 11:44:31
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Cell menu - All Output")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'test_editor_02.ipynb'
    test_editor_02_ipynb = driver.find_element(By.XPATH,
                                               "//span[. = 'test_editor_02.ipynb']")
    test_editor_02_ipynb.click()

    # 4. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 5. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 6. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 7. Click 'Toggle1'
    toggle1 = driver.find_element(By.XPATH,
                                  "//a[. = 'Toggle']")
    toggle1.click()

    # 8. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 9. Click 'Toggle Scrolling1'
    toggle_scrolling1 = driver.find_element(By.XPATH,
                                            "//a[. = 'Toggle Scrolling']")
    toggle_scrolling1.click()

    # 10. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 11. Click 'Clear1'
    clear1 = driver.find_element(By.XPATH,
                                 "//li[11]//a[. = 'Clear']")
    clear1.click()

    # 12. Type 'orld' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("orld")

    # 13. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 14. Click 'Toggle1'
    toggle1 = driver.find_element(By.XPATH,
                                  "//a[. = 'Toggle']")
    toggle1.click()

    # 15. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 16. Click 'Toggle Scrolling1'
    toggle_scrolling1 = driver.find_element(By.XPATH,
                                            "//a[. = 'Toggle Scrolling']")
    toggle_scrolling1.click()

    # 17. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 18. Click 'Clear1'
    clear1 = driver.find_element(By.XPATH,
                                 "//li[11]//a[. = 'Clear']")
    clear1.click()

    # 19. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 20. Click 'Run Cells'
    run_cells = driver.find_element(By.XPATH,
                                    "//span[. = 'Run Cells']")
    run_cells.click()

    # 21. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 22. Click 'Toggle1'
    toggle1 = driver.find_element(By.XPATH,
                                  "//a[. = 'Toggle']")
    toggle1.click()

    # 23. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 24. Click 'Toggle1'
    toggle1 = driver.find_element(By.XPATH,
                                  "//a[. = 'Toggle']")
    toggle1.click()

    # 25. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 26. Click 'Toggle Scrolling1'
    toggle_scrolling1 = driver.find_element(By.XPATH,
                                            "//a[. = 'Toggle Scrolling']")
    toggle_scrolling1.click()

    # 27. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 28. Click 'Clear1'
    clear1 = driver.find_element(By.XPATH,
                                 "//li[11]//a[. = 'Clear']")
    clear1.click()

    # 29. Type ')' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys(")")

    # 30. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 31. Click 'Run Cells⌃↩'
    run_cells_ = driver.find_element(By.XPATH,
                                     "//a[. = 'Run Cells⌃↩']")
    run_cells_.click()

    # 32. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 33. Click 'Toggle1'
    toggle1 = driver.find_element(By.XPATH,
                                  "//a[. = 'Toggle']")
    toggle1.click()

    # 34. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 35. Click 'Toggle1'
    toggle1 = driver.find_element(By.XPATH,
                                  "//a[. = 'Toggle']")
    toggle1.click()

    # 36. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 37. Click 'Toggle Scrolling1'
    toggle_scrolling1 = driver.find_element(By.XPATH,
                                            "//a[. = 'Toggle Scrolling']")
    toggle_scrolling1.click()

    # 38. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 39. Click 'Clear1'
    clear1 = driver.find_element(By.XPATH,
                                 "//li[11]//a[. = 'Clear']")
    clear1.click()

    # 40. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 41. Click 'Toggle1'
    toggle1 = driver.find_element(By.XPATH,
                                  "//a[. = 'Toggle']")
    toggle1.click()

    # 42. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 43. Click 'Toggle Scrolling1'
    toggle_scrolling1 = driver.find_element(By.XPATH,
                                            "//a[. = 'Toggle Scrolling']")
    toggle_scrolling1.click()

    # 44. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 45. Click 'Clear1'
    clear1 = driver.find_element(By.XPATH,
                                 "//li[11]//a[. = 'Clear']")
    clear1.click()

    # 46. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 47. Click 'DIV3'
    div3 = driver.find_element(By.XPATH,
                               "//div[2]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div")
    div3.click()

    # 48. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 49. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 50. Click 'Toggle1'
    toggle1 = driver.find_element(By.XPATH,
                                  "//a[. = 'Toggle']")
    toggle1.click()

    # 51. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 52. Click 'Toggle Scrolling1'
    toggle_scrolling1 = driver.find_element(By.XPATH,
                                            "//a[. = 'Toggle Scrolling']")
    toggle_scrolling1.click()

    # 53. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 54. Click 'Clear1'
    clear1 = driver.find_element(By.XPATH,
                                 "//li[11]//a[. = 'Clear']")
    clear1.click()

    # 55. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 56. Click 'Run All'
    run_all = driver.find_element(By.XPATH,
                                  "//a[. = 'Run All']")
    run_all.click()

    # 57. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 58. Click 'Toggle1'
    toggle1 = driver.find_element(By.XPATH,
                                  "//a[. = 'Toggle']")
    toggle1.click()

    # 59. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 60. Click 'Toggle1'
    toggle1 = driver.find_element(By.XPATH,
                                  "//a[. = 'Toggle']")
    toggle1.click()

    # 61. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 62. Click 'Toggle Scrolling1'
    toggle_scrolling1 = driver.find_element(By.XPATH,
                                            "//a[. = 'Toggle Scrolling']")
    toggle_scrolling1.click()

    # 63. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 64. Click 'Clear1'
    clear1 = driver.find_element(By.XPATH,
                                 "//li[11]//a[. = 'Clear']")
    clear1.click()

    # 65. Type ')' in 'TEXTAREA2'
    textarea2 = driver.find_element(By.XPATH,
                                    "//div[1]/div[1]/div[2]/div[2]//textarea")
    textarea2.send_keys(")")

    # 66. Type '10' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys("10")

    # 67. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 68. Click 'Toggle1'
    toggle1 = driver.find_element(By.XPATH,
                                  "//a[. = 'Toggle']")
    toggle1.click()

    # 69. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 70. Click 'Toggle Scrolling1'
    toggle_scrolling1 = driver.find_element(By.XPATH,
                                            "//a[. = 'Toggle Scrolling']")
    toggle_scrolling1.click()

    # 71. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 72. Click 'Clear1'
    clear1 = driver.find_element(By.XPATH,
                                 "//li[11]//a[. = 'Clear']")
    clear1.click()

    # 73. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 74. Click 'Run Cells'
    run_cells = driver.find_element(By.XPATH,
                                    "//span[. = 'Run Cells']")
    run_cells.click()

    # 75. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 76. Click 'Run Cells'
    run_cells = driver.find_element(By.XPATH,
                                    "//span[. = 'Run Cells']")
    run_cells.click()

    # 77. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 78. Click 'Toggle1'
    toggle1 = driver.find_element(By.XPATH,
                                  "//a[. = 'Toggle']")
    toggle1.click()

    # 79. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 80. Click 'Toggle1'
    toggle1 = driver.find_element(By.XPATH,
                                  "//a[. = 'Toggle']")
    toggle1.click()

    # 81. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 82. Click 'Toggle Scrolling1'
    toggle_scrolling1 = driver.find_element(By.XPATH,
                                            "//a[. = 'Toggle Scrolling']")
    toggle_scrolling1.click()

    # 83. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 84. Click 'Clear1'
    clear1 = driver.find_element(By.XPATH,
                                 "//li[11]//a[. = 'Clear']")
    clear1.click()

    # 85. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 86. Click 'Toggle1'
    toggle1 = driver.find_element(By.XPATH,
                                  "//a[. = 'Toggle']")
    toggle1.click()

    # 87. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 88. Click 'Toggle Scrolling1'
    toggle_scrolling1 = driver.find_element(By.XPATH,
                                            "//a[. = 'Toggle Scrolling']")
    toggle_scrolling1.click()

    # 89. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 90. Click 'Clear1'
    clear1 = driver.find_element(By.XPATH,
                                 "//li[11]//a[. = 'Clear']")
    clear1.click()

    # 91. Type 'Hello World' in 'TEXTAREA2'
    textarea2 = driver.find_element(By.XPATH,
                                    "//div[1]/div[1]/div[2]/div[2]//textarea")
    textarea2.send_keys("Hello World")

    # 92. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 93. Click 'Run All'
    run_all = driver.find_element(By.XPATH,
                                  "//a[. = 'Run All']")
    run_all.click()

    # 94. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 95. Click 'Toggle1'
    toggle1 = driver.find_element(By.XPATH,
                                  "//a[. = 'Toggle']")
    toggle1.click()

    # 96. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 97. Click 'Toggle1'
    toggle1 = driver.find_element(By.XPATH,
                                  "//a[. = 'Toggle']")
    toggle1.click()

    # 98. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 99. Click 'Toggle Scrolling1'
    toggle_scrolling1 = driver.find_element(By.XPATH,
                                            "//a[. = 'Toggle Scrolling']")
    toggle_scrolling1.click()

    # 100. Click 'Cell'
    cell = driver.find_element(By.CSS_SELECTOR,
                               "#celllink")
    cell.click()

    # 101. Click 'Clear1'
    clear1 = driver.find_element(By.XPATH,
                                 "//li[11]//a[. = 'Clear']")
    clear1.click()
