from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: TestProject.Generated.Tests.JupyterNotebookFunctionalTest
    Test: Built-in Functions
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/06/2021, 09:58:01
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Built-in Functions")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'New
    #
    #               ...'
    new_ = driver.find_element(By.CSS_SELECTOR,
                               "#new-dropdown-button")
    new_.click()

    # 4. Click 'Python 3'
    python_3 = driver.find_element(By.XPATH,
                                   "//a[. = 'Python 3']")
    python_3.click()

    # 5. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 6. Click 'Untitled6'
    untitled6 = driver.find_element(By.CSS_SELECTOR,
                                    "#notebook_name")
    untitled6.click()

    # 7. Type 'test_editor_05' in 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//input")
    input1.send_keys("test_editor_05")

    # 8. Click 'Rename2'
    rename2 = driver.find_element(By.XPATH,
                                  "//button[. = 'Rename']")
    rename2.click()

    # 9. Click 'DIV2'
    div2 = driver.find_element(By.XPATH,
                               "//div[6]/div[1]/div/div")
    div2.click()

    # 10. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 11. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 12. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 13. Type 'number' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("number")

    # 14. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 15. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 16. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 17. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 18. Type 'text' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys("text")

    # 19. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 20. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 21. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 22. Type 'rand_number' in 'TEXTAREA5'
    textarea5 = driver.find_element(By.XPATH,
                                    "//div[3]//textarea")
    textarea5.send_keys("rand_number")

    # 23. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 24. Type '1, 10' in 'TEXTAREA6'
    textarea6 = driver.find_element(By.XPATH,
                                    "//div[4]/div[1]/div[2]//textarea")
    textarea6.send_keys("1, 10")

    # 25. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 26. Click 'DIV18'
    div18 = driver.find_element(By.XPATH,
                                "//div[5]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div")
    div18.click()

    # 27. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 28. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 29. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 30. Click 'DIV19'
    div19 = driver.find_element(By.XPATH,
                                "//div[7]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div")
    div19.click()

    # 31. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 32. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 33. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 34. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 35. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 36. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 37. Type 'message2' in 'TEXTAREA13'
    textarea13 = driver.find_element(By.XPATH,
                                     "//div[8]//textarea")
    textarea13.send_keys("message2")

    # 38. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()
