from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: TestProject.Generated.Tests.JupyterNotebookFunctionalTest
    Test: IO Operation
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/06/2021, 09:59:04
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="IO Operation")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'New'
    new = driver.find_element(By.XPATH,
                              "//span[. = 'New']")
    new.click()

    # 4. Click 'Python 3'
    python_3 = driver.find_element(By.XPATH,
                                   "//a[. = 'Python 3']")
    python_3.click()

    # 5. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 6. Click 'Untitled6'
    untitled6 = driver.find_element(By.CSS_SELECTOR,
                                    "#notebook_name")
    untitled6.click()

    # 7. Type 'test_editor_08' in 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//input")
    input1.send_keys("test_editor_08")

    # 8. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 9. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 10. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 11. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 12. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 13. Click ''testjupyter.txt''
    _testjupyter_txt_ = driver.find_element(By.XPATH,
                                            "//div[2]/div[1]/div[2]//span[. = concat(\"'\", 'testjupyter.txt', \"'\")]")
    _testjupyter_txt_.click()

    # 14. Click ''testjupyter.txt''
    _testjupyter_txt_ = driver.find_element(By.XPATH,
                                            "//div[2]/div[1]/div[2]//span[. = concat(\"'\", 'testjupyter.txt', \"'\")]")
    _testjupyter_txt_.click()

    # 15. Type '_folder/' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys("_folder/")

    # 16. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 17. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 18. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 19. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 20. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 21. Click ''testjupyter.txt'1'
    _testjupyter_txt_1 = driver.find_element(By.XPATH,
                                             "//div[5]/pre//span[. = concat(\"'\", 'testjupyter.txt', \"'\")]")
    _testjupyter_txt_1.click()

    # 22. Click ''testjupyter.txt'1'
    _testjupyter_txt_1 = driver.find_element(By.XPATH,
                                             "//div[5]/pre//span[. = concat(\"'\", 'testjupyter.txt', \"'\")]")
    _testjupyter_txt_1.click()

    # 23. Click 'PRE17'
    pre17 = driver.find_element(By.XPATH,
                                "//div[7]/pre")
    pre17.click()

    # 24. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 25. Click '"testjupyter_write.txt"'
    _double_quote_testjupyter_write_txt_double_quote_ = driver.find_element(By.XPATH,
                                                                            "//div[4]/div[1]/div[2]//span[. = '&quot;testjupyter_write.txt&quot;']")
    _double_quote_testjupyter_write_txt_double_quote_.click()

    # 26. Click '"/non_existing_folder/testjupyter_wri...'
    _double_quote_slash_non_existing_folder_slash_testjupyter_wri_ = driver.find_element(By.XPATH,
                                                                                         "//span[. = '\"/non_existing_folder/testjupyter_write.txt\"']")
    _double_quote_slash_non_existing_folder_slash_testjupyter_wri_.click()

    # 27. Click ''testjupyter_write.txt''
    _testjupyter_write_txt_ = driver.find_element(By.XPATH,
                                                  "//div[4]/div[1]/div[2]//span[. = concat(\"'\", 'testjupyter_write.txt', \"'\")]")
    _testjupyter_write_txt_.click()

    # 28. Click 'PRE18'
    pre18 = driver.find_element(By.XPATH,
                                "//div[4]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div/div/div[5]/div[7]/pre")
    pre18.click()

    # 29. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()
