from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: TestProject.Generated.Tests.JupyterNotebookFunctionalTest
    Test: Class and Objects
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/06/2021, 09:58:22
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Class and Objects")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'SPAN'
    span = driver.find_element(By.XPATH,
                               "//div/div/div/div/div[1]/div[1]/div[2]/div/div[1]/button/span[2]")
    span.click()

    # 4. Click 'Python 3'
    python_3 = driver.find_element(By.XPATH,
                                   "//a[. = 'Python 3']")
    python_3.click()

    # 5. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 6. Click 'Untitled6'
    untitled6 = driver.find_element(By.CSS_SELECTOR,
                                    "#notebook_name")
    untitled6.click()

    # 7. Type 'test_editor_06' in 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//input")
    input1.send_keys("test_editor_06")

    # 8. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 9. Click '20'
    _20 = driver.find_element(By.XPATH,
                              "//div[2]/div[1]/div[2]//span[. = '20']")
    _20.click()

    # 10. Type ', ' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys(", ")

    # 11. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 12. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 13. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 14. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 15. Click 'DIV20'
    div20 = driver.find_element(By.XPATH,
                                "//div[4]/div[2]/div//div[3]")
    div20.click()

    # 16. Click 'PRE12'
    pre12 = driver.find_element(By.XPATH,
                                "//div[5]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div/div/div[5]/div[1]/pre")
    pre12.click()

    # 17. Click 'Random'
    random = driver.find_element(By.XPATH,
                                 "//div[1]/pre//span[. = 'Random']")
    random.click()

    # 18. Type '[NONE]' in 'TEXTAREA10'
    textarea10 = driver.find_element(By.XPATH,
                                     "//div[5]//textarea")
    textarea10.send_keys("")

    # 19. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 20. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 21. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 22. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 23. Type 'student1 = ' in 'TEXTAREA14'
    textarea14 = driver.find_element(By.XPATH,
                                     "//div[9]//textarea")
    textarea14.send_keys("student1 = ")

    # 24. Click 'PRE13'
    pre13 = driver.find_element(By.XPATH,
                                "//div[9]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div/div/div[5]/div[12]/pre")
    pre13.click()

    # 25. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 26. Click 'Run1'
    run1 = driver.find_element(By.XPATH,
                               "//button[. = 'Run']")
    run1.click()

    # 27. Click 'John 20 UOW123456 Australia'
    john_20_uow123456_australia = driver.find_element(By.XPATH,
                                                      "//pre[. = 'John 20 UOW123456 Australia\n']")
    john_20_uow123456_australia.click()

    # 28. Click 'SPAN6'
    span6 = driver.find_element(By.XPATH,
                                "//div[11]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div/div/div[5]/div[18]/pre/span")
    span6.click()

    # 29. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()
