from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: TestProject.Generated.Tests.JupyterNotebookFunctionalTest
    Test: Defining Functions
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/06/2021, 09:57:39
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Defining Functions")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'test_editor_04.ipynb'
    test_editor_04_ipynb = driver.find_element(By.XPATH,
                                               "//span[. = 'test_editor_04.ipynb']")
    test_editor_04_ipynb.click()

    # 4. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 5. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 6. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 7. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 8. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 9. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 10. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 11. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 12. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 13. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 14. Type 'ABC' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys("ABC")

    # 15. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 16. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 17. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 18. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 19. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 20. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 21. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 22. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 23. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 24. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 25. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 26. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 27. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 28. Type 'func' in 'TEXTAREA6'
    textarea6 = driver.find_element(By.XPATH,
                                    "//div[4]/div[1]/div[2]//textarea")
    textarea6.send_keys("func")

    # 29. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 30. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 31. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 32. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 33. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 34. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 35. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 36. Type 'func' in 'TEXTAREA10'
    textarea10 = driver.find_element(By.XPATH,
                                     "//div[5]//textarea")
    textarea10.send_keys("func")

    # 37. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 38. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 39. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 40. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 41. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 42. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 43. Type 'func' in 'TEXTAREA11'
    textarea11 = driver.find_element(By.XPATH,
                                     "//div[6]//textarea")
    textarea11.send_keys("func")

    # 44. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 45. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 46. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 47. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 48. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 49. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 50. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 51. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 52. Type 'func' in 'TEXTAREA12'
    textarea12 = driver.find_element(By.XPATH,
                                     "//div[7]//textarea")
    textarea12.send_keys("func")

    # 53. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 54. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 55. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 56. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 57. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 58. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 59. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 60. Type 'func' in 'TEXTAREA13'
    textarea13 = driver.find_element(By.XPATH,
                                     "//div[8]//textarea")
    textarea13.send_keys("func")

    # 61. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 62. Click '"Default"'
    _double_quote_default_double_quote_ = driver.find_element(By.XPATH,
                                                              "//div[9]//span[. = '&quot;Default&quot;']")
    _double_quote_default_double_quote_.click()

    # 63. Type 'Test Message' in 'TEXTAREA14'
    textarea14 = driver.find_element(By.XPATH,
                                     "//div[9]//textarea")
    textarea14.send_keys("Test Message")

    # 64. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 65. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 66. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 67. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 68. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 69. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 70. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 71. Click 'Run1'
    run1 = driver.find_element(By.XPATH,
                               "//button[. = 'Run']")
    run1.click()

    # 72. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 73. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 74. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 75. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 76. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 77. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 78. Click 'PRE7'
    pre7 = driver.find_element(By.XPATH,
                               "//div[11]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div/div/div[5]/div[6]/pre")
    pre7.click()

    # 79. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 80. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 81. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 82. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 83. Click 'PRE8'
    pre8 = driver.find_element(By.XPATH,
                               "//div[12]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div/div/div[5]/div[2]/pre")
    pre8.click()

    # 84. Click 'PRE8'
    pre8 = driver.find_element(By.XPATH,
                               "//div[12]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div/div/div[5]/div[2]/pre")
    pre8.click()

    # 85. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 86. Type '2' in 'TEXTAREA17'
    textarea17 = driver.find_element(By.XPATH,
                                     "//div[12]//textarea")
    textarea17.send_keys("2")

    # 87. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 88. Click '"This is the result from func_a: "'
    _double_quote_this_is_the_result_from_func_a_colon_double_quote_ = driver.find_element(By.XPATH,
                                                                                           "//div[13]//span[. = '&quot;This is the result from func_a: &quot;']")
    _double_quote_this_is_the_result_from_func_a_colon_double_quote_.click()

    # 89. Click '"This is the final result from func_a...'
    _double_quote_this_is_the_final_result_from_func_a_ = driver.find_element(By.XPATH,
                                                                              "//span[. = '\"This is the final result from func_a: \"']")
    _double_quote_this_is_the_final_result_from_func_a_.click()

    # 90. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 91. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 92. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 93. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 94. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 95. Type '5' in 'TEXTAREA18'
    textarea18 = driver.find_element(By.XPATH,
                                     "//div[13]//textarea")
    textarea18.send_keys("5")

    # 96. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 97. Click 'message'
    message = driver.find_element(By.XPATH,
                                  "//div[14]//span[1][. = 'message']")
    message.click()

    # 98. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 99. Click '8'
    _8 = driver.find_element(By.XPATH,
                             "//div[14]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div/div/div[5]/div[11]/pre[. = '    ']")
    _8.click()

    # 100. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 101. Click '"This is the result from func_a: "1'
    _double_quote_this_is_the_result_from_func_a_colon_double_quote_1 = driver.find_element(By.XPATH,
                                                                                            "//div[15]//span[. = '&quot;This is the result from func_a: &quot;']")
    _double_quote_this_is_the_result_from_func_a_colon_double_quote_1.click()

    # 102. Click 'SPAN4'
    span4 = driver.find_element(By.XPATH,
                                "//div[15]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div/div/div[5]/div[7]/pre/span")
    span4.click()

    # 103. Type '[NONE]' in 'TEXTAREA20'
    textarea20 = driver.find_element(By.XPATH,
                                     "//div[15]//textarea")
    textarea20.send_keys("")

    # 104. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 105. Click 'PRE9'
    pre9 = driver.find_element(By.XPATH,
                               "//div[16]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div/div/div[5]/div[4]/pre")
    pre9.click()

    # 106. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 107. Type 'message' in 'TEXTAREA21'
    textarea21 = driver.find_element(By.XPATH,
                                     "//div[16]//textarea")
    textarea21.send_keys("message")

    # 108. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 109. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 110. Type 'func' in 'TEXTAREA21'
    textarea21 = driver.find_element(By.XPATH,
                                     "//div[16]//textarea")
    textarea21.send_keys("func")

    # 111. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 112. Click 'PRE10'
    pre10 = driver.find_element(By.XPATH,
                                "//div[17]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div/div/div[5]/div[6]/pre")
    pre10.click()

    # 113. Click 'print'
    print = driver.find_element(By.XPATH,
                                "//div[17]//span[. = 'print']")
    print.click()

    # 114. Type 'result' in 'TEXTAREA22'
    textarea22 = driver.find_element(By.XPATH,
                                     "//div[17]//textarea")
    textarea22.send_keys("result")

    # 115. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 116. Type 'return message_a, message_b' in 'TEXTAREA22'
    textarea22 = driver.find_element(By.XPATH,
                                     "//div[17]//textarea")
    textarea22.send_keys("return message_a, message_b")

    # 117. Click 'Run1'
    run1 = driver.find_element(By.XPATH,
                               "//button[. = 'Run']")
    run1.click()

    # 118. Click 'DIV17'
    div17 = driver.find_element(By.XPATH,
                                "//div[18]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div")
    div17.click()

    # 119. Type 'lt' in 'TEXTAREA23'
    textarea23 = driver.find_element(By.XPATH,
                                     "//div[18]//textarea")
    textarea23.send_keys("lt")
