from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: TestProject.Generated.Tests.JupyterNotebookFunctionalTest
    Test: Data Types
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/06/2021, 09:57:21
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Data Types")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'test_editor_03.ipynb'
    test_editor_03_ipynb = driver.find_element(By.XPATH,
                                               "//span[. = 'test_editor_03.ipynb']")
    test_editor_03_ipynb.click()

    # 4. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 5. Click 'DIV15'
    div15 = driver.find_element(By.XPATH,
                                "//div/div/div/div[1]/div[1]/div/div[1]/div[2]/div[2]")
    div15.click()

    # 6. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 7. Type 'text' in 'TEXTAREA4'
    textarea4 = driver.find_element(By.XPATH,
                                    "//textarea")
    textarea4.send_keys("text")

    # 8. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 9. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 10. Type 'number' in 'TEXTAREA3'
    textarea3 = driver.find_element(By.XPATH,
                                    "//div[2]/div[1]/div[2]//textarea")
    textarea3.send_keys("number")

    # 11. Click 'Run1'
    run1 = driver.find_element(By.XPATH,
                               "//button[. = 'Run']")
    run1.click()

    # 12. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 13. Type 'number' in 'TEXTAREA5'
    textarea5 = driver.find_element(By.XPATH,
                                    "//div[3]//textarea")
    textarea5.send_keys("number")

    # 14. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 15. Click 'DIV13'
    div13 = driver.find_element(By.XPATH,
                                "//div[4]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div")
    div13.click()

    # 16. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 17. Type 'condition' in 'TEXTAREA6'
    textarea6 = driver.find_element(By.XPATH,
                                    "//div[4]/div[1]/div[2]//textarea")
    textarea6.send_keys("condition")

    # 18. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 19. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 20. Type 'list1' in 'TEXTAREA10'
    textarea10 = driver.find_element(By.XPATH,
                                     "//div[5]//textarea")
    textarea10.send_keys("list1")

    # 21. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 22. Click 'DIV16'
    div16 = driver.find_element(By.XPATH,
                                "//div[6]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div")
    div16.click()

    # 23. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 24. Type 'tup1' in 'TEXTAREA11'
    textarea11 = driver.find_element(By.XPATH,
                                     "//div[6]//textarea")
    textarea11.send_keys("tup1")

    # 25. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 26. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 27. Type ')' in 'TEXTAREA12'
    textarea12 = driver.find_element(By.XPATH,
                                     "//div[7]//textarea")
    textarea12.send_keys(")")

    # 28. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 29. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 30. Type ')' in 'TEXTAREA13'
    textarea13 = driver.find_element(By.XPATH,
                                     "//div[8]//textarea")
    textarea13.send_keys(")")

    # 31. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()
