from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: TestProject.Generated.Tests.JupyterNotebookFunctionalTest
    Test: Batch Operations - Multiple Selection
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/24/2021, 04:15:40
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Batch Operations - Multiple Selection")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'SPAN1'
    span1 = driver.find_element(By.XPATH,
                                "//body/div[1]//span[1]")
    span1.click()

    # 3. Click 'checkbox
    #
    #          ...'
    checkbox_ = driver.find_element(By.CSS_SELECTOR,
                                    "#tree-selector-btn")
    checkbox_.click()

    # 4. Click 'Folders'
    folders = driver.find_element(By.CSS_SELECTOR,
                                  "#select-folders")
    folders.click()

    # 5. Click 'SPAN2'
    span2 = driver.find_element(By.XPATH,
                                "//button[2]/span[2]")
    span2.click()

    # 6. Click 'All Notebooks'
    all_notebooks = driver.find_element(By.CSS_SELECTOR,
                                        "#select-notebooks")
    all_notebooks.click()

    # 7. Click 'checkbox
    #
    #          ...'
    checkbox_ = driver.find_element(By.CSS_SELECTOR,
                                    "#tree-selector-btn")
    checkbox_.click()

    # 8. Click 'Running1'
    running1 = driver.find_element(By.CSS_SELECTOR,
                                   "#select-running-notebooks")
    running1.click()

    # 9. Click 'checkbox
    #
    #          ...'
    checkbox_ = driver.find_element(By.CSS_SELECTOR,
                                    "#tree-selector-btn")
    checkbox_.click()

    # 10. Click 'Files1'
    files1 = driver.find_element(By.CSS_SELECTOR,
                                 "#select-files")
    files1.click()

    # 11. Click 'checkbox
    #
    #          ...'
    checkbox_ = driver.find_element(By.CSS_SELECTOR,
                                    "#tree-selector-btn")
    checkbox_.click()

    # 12. Click 'select-all'
    select_all = driver.find_element(By.CSS_SELECTOR,
                                     "#select-all")
    select_all.click()

    # 13. Click 'select-all'
    select_all = driver.find_element(By.CSS_SELECTOR,
                                     "#select-all")
    select_all.click()

    # 14. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 15. Click 'Click here to rename, delete, etc.2'
    click_here_to_rename_delete_etc_2 = driver.find_element(By.XPATH,
                                                            "//div[4]//input")
    click_here_to_rename_delete_etc_2.click()

    # 16. Click 'Click here to rename, delete, etc.19'
    click_here_to_rename_delete_etc_19 = driver.find_element(By.XPATH,
                                                             "//div[9]//input")
    click_here_to_rename_delete_etc_19.click()

    # 17. Click 'Duplicate'
    duplicate = driver.find_element(By.XPATH,
                                    "//button[. = 'Duplicate ']")
    duplicate.click()

    # 18. Click 'Duplicate1'
    duplicate1 = driver.find_element(By.XPATH,
                                     "//button[. = 'Duplicate']")
    duplicate1.click()

    # 19. Click 'Click here to rename, delete, etc.19'
    click_here_to_rename_delete_etc_19 = driver.find_element(By.XPATH,
                                                             "//div[9]//input")
    click_here_to_rename_delete_etc_19.click()

    # 20. Click 'Click here to rename, delete, etc.21'
    click_here_to_rename_delete_etc_21 = driver.find_element(By.XPATH,
                                                             "//div[11]//input")
    click_here_to_rename_delete_etc_21.click()

    # 21. Click 'Shutdown'
    shutdown = driver.find_element(By.XPATH,
                                   "//button[5][. = 'Shutdown']")
    shutdown.click()

    # 22. Click 'Click here to rename, delete, etc.22'
    click_here_to_rename_delete_etc_22 = driver.find_element(By.XPATH,
                                                             "//div[12]//input")
    click_here_to_rename_delete_etc_22.click()

    # 23. Click 'Click here to rename, delete, etc.23'
    click_here_to_rename_delete_etc_23 = driver.find_element(By.XPATH,
                                                             "//div[13]//input")
    click_here_to_rename_delete_etc_23.click()

    # 24. Click 'I3'
    i3 = driver.find_element(By.XPATH,
                             "//button[8]/i")
    i3.click()

    # 25. Click 'Delete'
    delete = driver.find_element(By.XPATH,
                                 "//button[. = 'Delete']")
    delete.click()

    # 26. Click 'Click here to rename, delete, etc.4'
    click_here_to_rename_delete_etc_4 = driver.find_element(By.XPATH,
                                                            "//div[6]//input")
    click_here_to_rename_delete_etc_4.click()

    # 27. Click 'Click here to rename, delete, etc.22'
    click_here_to_rename_delete_etc_22 = driver.find_element(By.XPATH,
                                                             "//div[12]//input")
    click_here_to_rename_delete_etc_22.click()

    # 28. Click 'Duplicate'
    duplicate = driver.find_element(By.XPATH,
                                    "//button[. = 'Duplicate ']")
    duplicate.click()

    # 29. Click 'Duplicate1'
    duplicate1 = driver.find_element(By.XPATH,
                                     "//button[. = 'Duplicate']")
    duplicate1.click()

    # 30. Click 'Click here to rename, delete, etc.5'
    click_here_to_rename_delete_etc_5 = driver.find_element(By.XPATH,
                                                            "//div[7]//input")
    click_here_to_rename_delete_etc_5.click()

    # 31. Click 'Click here to rename, delete, etc.24'
    click_here_to_rename_delete_etc_24 = driver.find_element(By.XPATH,
                                                             "//div[14]//input")
    click_here_to_rename_delete_etc_24.click()

    # 32. Click 'Shutdown'
    shutdown = driver.find_element(By.XPATH,
                                   "//button[5][. = 'Shutdown']")
    shutdown.click()

    # 33. Click 'Click here to rename, delete, etc.4'
    click_here_to_rename_delete_etc_4 = driver.find_element(By.XPATH,
                                                            "//div[6]//input")
    click_here_to_rename_delete_etc_4.click()

    # 34. Click 'Click here to rename, delete, etc.25'
    click_here_to_rename_delete_etc_25 = driver.find_element(By.XPATH,
                                                             "//div[16]//input")
    click_here_to_rename_delete_etc_25.click()

    # 35. Click 'I3'
    i3 = driver.find_element(By.XPATH,
                             "//button[8]/i")
    i3.click()

    # 36. Click 'Delete'
    delete = driver.find_element(By.XPATH,
                                 "//button[. = 'Delete']")
    delete.click()
