from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: EditMenuMetadata
    Test: Edit Menu - Metadata
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 04/27/2021, 06:38:36
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Edit Menu - Metadata")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'test_editor_01.ipynb1'
    test_editor_01_ipynb1 = driver.find_element(By.XPATH,
                                                "//span[. = 'test_editor_01.ipynb']")
    test_editor_01_ipynb1.click()

    # 4. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 5. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 6. Click 'Edit Notebook Metadata'
    edit_notebook_metadata = driver.find_element(By.XPATH,
                                                 "//a[. = 'Edit Notebook Metadata']")
    edit_notebook_metadata.click()

    # 7. Click 'Edit2'
    edit2 = driver.find_element(By.XPATH,
                                "//button[. = 'Edit']")
    edit2.click()

    # 8. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 9. Click 'Edit Notebook Metadata'
    edit_notebook_metadata = driver.find_element(By.XPATH,
                                                 "//a[. = 'Edit Notebook Metadata']")
    edit_notebook_metadata.click()

    # 10. Click 'Cancel1'
    cancel1 = driver.find_element(By.XPATH,
                                  "//button[. = 'Cancel']")
    cancel1.click()

    # 11. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 12. Click 'Edit Notebook Metadata'
    edit_notebook_metadata = driver.find_element(By.XPATH,
                                                 "//a[. = 'Edit Notebook Metadata']")
    edit_notebook_metadata.click()

    # 13. Click '"language": "python"'
    _double_quote_language_double_quote_colon_double_quote_python_double_quote_ = driver.find_element(By.XPATH,
                                                                                                      "//span[. = '    \"language\": \"python\"']")
    _double_quote_language_double_quote_colon_double_quote_python_double_quote_.click()

    # 14. Type 'java' in 'TEXTAREA'
    textarea = driver.find_element(By.XPATH,
                                   "//div[2]/div/textarea")
    textarea.send_keys("java")

    # 15. Click 'Edit2'
    edit2 = driver.find_element(By.XPATH,
                                "//button[. = 'Edit']")
    edit2.click()

    # 16. Click 'DIV5'
    div5 = driver.find_element(By.XPATH,
                               "//div[4]/div/div/div[1]/div/div")
    div5.click()

    # 17. Click 'I4'
    i4 = driver.find_element(By.XPATH,
                             "//div[5]/button[1]/i")
    i4.click()

    # 18. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 19. Click 'Edit Notebook Metadata'
    edit_notebook_metadata = driver.find_element(By.XPATH,
                                                 "//a[. = 'Edit Notebook Metadata']")
    edit_notebook_metadata.click()
