from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: EditMenuInsertImage
    Test: Edit Menu - Insert Image
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 04/27/2021, 06:40:24
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Edit Menu - Insert Image")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'test_editor_01.ipynb1'
    test_editor_01_ipynb1 = driver.find_element(By.XPATH,
                                                "//span[. = 'test_editor_01.ipynb']")
    test_editor_01_ipynb1.click()

    # 4. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 5. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 6. Click 'Insert Image'
    insert_image = driver.find_element(By.XPATH,
                                       "//a[. = '  Insert Image ']")
    insert_image.click()

    # 7. Click 'cell_type'
    cell_type = driver.find_element(By.CSS_SELECTOR,
                                    "#cell_type")
    cell_type.click()

    # 8. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 9. Click 'DIV3'
    div3 = driver.find_element(By.XPATH,
                               "//div[2]/div[1]/div[2]/div[2]/div/div[6]/div[1]/div/div")
    div3.click()

    # 10. Click 'cell_type'
    cell_type = driver.find_element(By.CSS_SELECTOR,
                                    "#cell_type")
    cell_type.click()

    # 11. Select the 'markdown' option in 'cell_type'
    cell_type = driver.find_element(By.CSS_SELECTOR,
                                    "#cell_type")
    Select(cell_type).select_by_value("markdown")

    # 12. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 13. Click 'Insert Image'
    insert_image = driver.find_element(By.XPATH,
                                       "//a[. = '  Insert Image ']")
    insert_image.click()

    # 14. Click 'file1'
    file1 = driver.find_element(By.CSS_SELECTOR,
                                "[name='file']")
    file1.click()

    # 15. Type 'C:\fakepath\testjupyter.png' in 'file1'
    file1 = driver.find_element(By.CSS_SELECTOR,
                                "[name='file']")
    file1.send_keys("C:\\fakepath\\testjupyter.png")

    # 16. Click 'OK2'
    ok2 = driver.find_element(By.CSS_SELECTOR,
                              "#btn_ok")
    ok2.click()

    # 17. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 18. Click 'cell_type'
    cell_type = driver.find_element(By.CSS_SELECTOR,
                                    "#cell_type")
    cell_type.click()

    # 19. Select the 'raw' option in 'cell_type'
    cell_type = driver.find_element(By.CSS_SELECTOR,
                                    "#cell_type")
    Select(cell_type).select_by_value("raw")

    # 20. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 21. Click 'Insert Image'
    insert_image = driver.find_element(By.XPATH,
                                       "//a[. = '  Insert Image ']")
    insert_image.click()

    # 22. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 23. Click 'cell_type'
    cell_type = driver.find_element(By.CSS_SELECTOR,
                                    "#cell_type")
    cell_type.click()

    # 24. Select the 'heading' option in 'cell_type'
    cell_type = driver.find_element(By.CSS_SELECTOR,
                                    "#cell_type")
    Select(cell_type).select_by_value("heading")

    # 25. Click 'OK3'
    ok3 = driver.find_element(By.XPATH,
                              "//button[. = 'OK']")
    ok3.click()

    # 26. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 27. Click 'Insert Image'
    insert_image = driver.find_element(By.XPATH,
                                       "//a[. = '  Insert Image ']")
    insert_image.click()

    # 28. Click 'file1'
    file1 = driver.find_element(By.CSS_SELECTOR,
                                "[name='file']")
    file1.click()

    # 29. Type 'C:\fakepath\testjupyter.png' in 'file1'
    file1 = driver.find_element(By.CSS_SELECTOR,
                                "[name='file']")
    file1.send_keys("C:\\fakepath\\testjupyter.png")

    # 30. Click 'OK2'
    ok2 = driver.find_element(By.CSS_SELECTOR,
                              "#btn_ok")
    ok2.click()
