from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: EditMenuFindAndReplace
    Test: Edit Menu - Find and Replace
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 04/27/2021, 06:39:17
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Edit Menu - Find and Replace")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'test_editor_01.ipynb1'
    test_editor_01_ipynb1 = driver.find_element(By.XPATH,
                                                "//span[. = 'test_editor_01.ipynb']")
    test_editor_01_ipynb1.click()

    # 4. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 5. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 6. Click 'Find and Replace'
    find_and_replace = driver.find_element(By.XPATH,
                                           "//a[. = ' Find and Replace ']")
    find_and_replace.click()

    # 7. Type 'Hello' in 'Find'
    find = driver.find_element(By.CSS_SELECTOR,
                               "#findreplace_find_inp")
    find.send_keys("Hello")

    # 8. Type 'heLLO' in 'Replace'
    replace = driver.find_element(By.CSS_SELECTOR,
                                  "#findreplace_replace_inp")
    replace.send_keys("heLLO")

    # 9. Click 'Replace All'
    replace_all = driver.find_element(By.CSS_SELECTOR,
                                      "#findreplace_replaceall_btn")
    replace_all.click()

    # 10. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 11. Click 'Find and Replace'
    find_and_replace = driver.find_element(By.XPATH,
                                           "//a[. = ' Find and Replace ']")
    find_and_replace.click()

    # 12. Click 'Aa'
    aa = driver.find_element(By.XPATH,
                             "//button[. = 'Aa']")
    aa.click()

    # 13. Click 'Find'
    find = driver.find_element(By.CSS_SELECTOR,
                               "#findreplace_find_inp")
    find.click()

    # 14. Type 'heLLo' in 'Find'
    find = driver.find_element(By.CSS_SELECTOR,
                               "#findreplace_find_inp")
    find.send_keys("heLLo")

    # 15. Type 'hello' in 'Replace'
    replace = driver.find_element(By.CSS_SELECTOR,
                                  "#findreplace_replace_inp")
    replace.send_keys("hello")

    # 16. Click 'Replace All'
    replace_all = driver.find_element(By.CSS_SELECTOR,
                                      "#findreplace_replaceall_btn")
    replace_all.click()

    # 17. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 18. Click 'Find and Replace'
    find_and_replace = driver.find_element(By.XPATH,
                                           "//a[. = ' Find and Replace ']")
    find_and_replace.click()

    # 19. Click '.*'
    _asterisk_ = driver.find_element(By.CSS_SELECTOR,
                                     "#isreg")
    _asterisk_.click()

    # 20. Click 'Find'
    find = driver.find_element(By.CSS_SELECTOR,
                               "#findreplace_find_inp")
    find.click()

    # 21. Type 'el' in 'Find'
    find = driver.find_element(By.CSS_SELECTOR,
                               "#findreplace_find_inp")
    find.send_keys("el")

    # 22. Click 'Replace'
    replace = driver.find_element(By.CSS_SELECTOR,
                                  "#findreplace_replace_inp")
    replace.click()

    # 23. Type 'al' in 'Replace'
    replace = driver.find_element(By.CSS_SELECTOR,
                                  "#findreplace_replace_inp")
    replace.send_keys("al")

    # 24. Click 'Replace All'
    replace_all = driver.find_element(By.CSS_SELECTOR,
                                      "#findreplace_replaceall_btn")
    replace_all.click()

    # 25. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 26. Click 'Find and Replace'
    find_and_replace = driver.find_element(By.XPATH,
                                           "//a[. = ' Find and Replace ']")
    find_and_replace.click()

    # 27. Click 'Replace in all cells'
    replace_in_all_cells = driver.find_element(By.CSS_SELECTOR,
                                               "#findreplace_allcells_btn")
    replace_in_all_cells.click()

    # 28. Click 'Find'
    find = driver.find_element(By.CSS_SELECTOR,
                               "#findreplace_find_inp")
    find.click()

    # 29. Type 'al' in 'Find'
    find = driver.find_element(By.CSS_SELECTOR,
                               "#findreplace_find_inp")
    find.send_keys("al")

    # 30. Type 'EL' in 'Replace'
    replace = driver.find_element(By.CSS_SELECTOR,
                                  "#findreplace_replace_inp")
    replace.send_keys("EL")

    # 31. Click 'Replace All'
    replace_all = driver.find_element(By.CSS_SELECTOR,
                                      "#findreplace_replaceall_btn")
    replace_all.click()

    # 32. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 33. Click 'Find and Replace'
    find_and_replace = driver.find_element(By.XPATH,
                                           "//a[. = ' Find and Replace ']")
    find_and_replace.click()

    # 34. Click 'Find'
    find = driver.find_element(By.CSS_SELECTOR,
                               "#findreplace_find_inp")
    find.click()

    # 35. Type 'apple' in 'Find'
    find = driver.find_element(By.CSS_SELECTOR,
                               "#findreplace_find_inp")
    find.send_keys("apple")

    # 36. Type 'orange' in 'Replace'
    replace = driver.find_element(By.CSS_SELECTOR,
                                  "#findreplace_replace_inp")
    replace.send_keys("orange")

    # 37. Click 'Replace All'
    replace_all = driver.find_element(By.CSS_SELECTOR,
                                      "#findreplace_replaceall_btn")
    replace_all.click()

    # 38. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 39. Click 'Find and Replace'
    find_and_replace = driver.find_element(By.XPATH,
                                           "//a[. = ' Find and Replace ']")
    find_and_replace.click()

    # 40. Click 'Aa'
    aa = driver.find_element(By.XPATH,
                             "//button[. = 'Aa']")
    aa.click()

    # 41. Click 'Aa'
    aa = driver.find_element(By.XPATH,
                             "//button[. = 'Aa']")
    aa.click()

    # 42. Click 'Find'
    find = driver.find_element(By.CSS_SELECTOR,
                               "#findreplace_find_inp")
    find.click()

    # 43. Type 'apple' in 'Find'
    find = driver.find_element(By.CSS_SELECTOR,
                               "#findreplace_find_inp")
    find.send_keys("apple")

    # 44. Type 'orange' in 'Replace'
    replace = driver.find_element(By.CSS_SELECTOR,
                                  "#findreplace_replace_inp")
    replace.send_keys("orange")

    # 45. Click 'Replace All'
    replace_all = driver.find_element(By.CSS_SELECTOR,
                                      "#findreplace_replaceall_btn")
    replace_all.click()

    # 46. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 47. Click 'Find and Replace'
    find_and_replace = driver.find_element(By.XPATH,
                                           "//a[. = ' Find and Replace ']")
    find_and_replace.click()

    # 48. Click '.*'
    _asterisk_ = driver.find_element(By.CSS_SELECTOR,
                                     "#isreg")
    _asterisk_.click()

    # 49. Click 'Find'
    find = driver.find_element(By.CSS_SELECTOR,
                               "#findreplace_find_inp")
    find.click()

    # 50. Type 'apple' in 'Find'
    find = driver.find_element(By.CSS_SELECTOR,
                               "#findreplace_find_inp")
    find.send_keys("apple")

    # 51. Type 'orange' in 'Replace'
    replace = driver.find_element(By.CSS_SELECTOR,
                                  "#findreplace_replace_inp")
    replace.send_keys("orange")

    # 52. Click 'Replace All'
    replace_all = driver.find_element(By.CSS_SELECTOR,
                                      "#findreplace_replaceall_btn")
    replace_all.click()

    # 53. Click 'Edit1'
    edit1 = driver.find_element(By.CSS_SELECTOR,
                                "#editlink")
    edit1.click()

    # 54. Click 'Find and Replace'
    find_and_replace = driver.find_element(By.XPATH,
                                           "//a[. = ' Find and Replace ']")
    find_and_replace.click()

    # 55. Click 'Find'
    find = driver.find_element(By.CSS_SELECTOR,
                               "#findreplace_find_inp")
    find.click()

    # 56. Click 'Replace in all cells'
    replace_in_all_cells = driver.find_element(By.CSS_SELECTOR,
                                               "#findreplace_allcells_btn")
    replace_in_all_cells.click()

    # 57. Click 'Find'
    find = driver.find_element(By.CSS_SELECTOR,
                               "#findreplace_find_inp")
    find.click()

    # 58. Type 'apple' in 'Find'
    find = driver.find_element(By.CSS_SELECTOR,
                               "#findreplace_find_inp")
    find.send_keys("apple")

    # 59. Type 'orange' in 'Replace'
    replace = driver.find_element(By.CSS_SELECTOR,
                                  "#findreplace_replace_inp")
    replace.send_keys("orange")

    # 60. Click 'Replace All'
    replace_all = driver.find_element(By.CSS_SELECTOR,
                                      "#findreplace_replaceall_btn")
    replace_all.click()
