from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: ViewMenuToggle
    Test: View Menu - Toggle
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/01/2021, 01:44:07
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="View Menu - Toggle")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'test_editor_01.ipynb1'
    test_editor_01_ipynb1 = driver.find_element(By.XPATH,
                                                "//span[. = 'test_editor_01.ipynb']")
    test_editor_01_ipynb1.click()

    # 4. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 5. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 6. Click 'Toggle Header'
    toggle_header = driver.find_element(By.XPATH,
                                        "//a[. = 'Toggle Header']")
    toggle_header.click()

    # 7. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 8. Click 'Toggle Toolbar'
    toggle_toolbar = driver.find_element(By.XPATH,
                                         "//a[. = 'Toggle Toolbar']")
    toggle_toolbar.click()

    # 9. Click '​3'
    _3 = driver.find_element(By.XPATH,
                             "//div[3]//pre[. = '​']")
    _3.click()

    # 10. Type ' tool bar' in 'TEXTAREA1'
    textarea1 = driver.find_element(By.XPATH,
                                    "//div[3]//textarea")
    textarea1.send_keys(" tool bar")

    # 11. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 12. Click 'Toggle Toolbar'
    toggle_toolbar = driver.find_element(By.XPATH,
                                         "//a[. = 'Toggle Toolbar']")
    toggle_toolbar.click()

    # 13. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 14. Click 'Toggle Toolbar'
    toggle_toolbar = driver.find_element(By.XPATH,
                                         "//a[. = 'Toggle Toolbar']")
    toggle_toolbar.click()

    # 15. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 16. Click 'Toggle Header'
    toggle_header = driver.find_element(By.XPATH,
                                        "//a[. = 'Toggle Header']")
    toggle_header.click()

    # 17. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 18. Click 'Toggle Line Numbers'
    toggle_line_numbers = driver.find_element(By.XPATH,
                                              "//span[. = 'Toggle Line Numbers']")
    toggle_line_numbers.click()

    # 19. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 20. Click 'Toggle Line Numbers'
    toggle_line_numbers = driver.find_element(By.XPATH,
                                              "//span[. = 'Toggle Line Numbers']")
    toggle_line_numbers.click()

    # 21. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 22. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 23. Click 'Toggle Toolbar'
    toggle_toolbar = driver.find_element(By.XPATH,
                                         "//a[. = 'Toggle Toolbar']")
    toggle_toolbar.click()

    # 24. Click 'I5'
    i5 = driver.find_element(By.XPATH,
                             "//div[2]/button/i")
    i5.click()

    # 25. Click 'insert cell below'
    insert_cell_below = driver.find_element(By.XPATH,
                                            "//div[2]/button")
    insert_cell_below.click()

    # 26. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 27. Click 'Toggle Line Numbers'
    toggle_line_numbers = driver.find_element(By.XPATH,
                                              "//span[. = 'Toggle Line Numbers']")
    toggle_line_numbers.click()

    # 28. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 29. Click 'Toggle Line Numbers'
    toggle_line_numbers = driver.find_element(By.XPATH,
                                              "//span[. = 'Toggle Line Numbers']")
    toggle_line_numbers.click()
