from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: ViewMenuCellToolbar
    Test: View Menu - Cell Toolbar
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/01/2021, 01:44:45
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="View Menu - Cell Toolbar")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'test_editor_01.ipynb1'
    test_editor_01_ipynb1 = driver.find_element(By.XPATH,
                                                "//span[. = 'test_editor_01.ipynb']")
    test_editor_01_ipynb1.click()

    # 4. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 5. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 6. Click 'None'
    none = driver.find_element(By.XPATH,
                               "//a[. = 'None']")
    none.click()

    # 7. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 8. Click 'Edit Metadata'
    edit_metadata = driver.find_element(By.XPATH,
                                        "//a[. = 'Edit Metadata']")
    edit_metadata.click()

    # 9. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 10. Click 'Raw Cell Format'
    raw_cell_format = driver.find_element(By.XPATH,
                                          "//a[. = 'Raw Cell Format']")
    raw_cell_format.click()

    # 11. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 12. Click 'Slideshow'
    slideshow = driver.find_element(By.XPATH,
                                    "//a[. = 'Slideshow']")
    slideshow.click()

    # 13. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 14. Click 'SELECT'
    select = driver.find_element(By.XPATH,
                                 "//div[1]/div[1]/div[2]/div[1]//select")
    select.click()

    # 15. Select the 'slide' option in 'SELECT'
    select = driver.find_element(By.XPATH,
                                 "//div[1]/div[1]/div[2]/div[1]//select")
    Select(select).select_by_value("slide")

    # 16. Click 'SELECT'
    select = driver.find_element(By.XPATH,
                                 "//div[1]/div[1]/div[2]/div[1]//select")
    select.click()

    # 17. Select the 'subslide' option in 'SELECT'
    select = driver.find_element(By.XPATH,
                                 "//div[1]/div[1]/div[2]/div[1]//select")
    Select(select).select_by_value("subslide")

    # 18. Click 'SELECT'
    select = driver.find_element(By.XPATH,
                                 "//div[1]/div[1]/div[2]/div[1]//select")
    select.click()

    # 19. Select the 'fragment' option in 'SELECT'
    select = driver.find_element(By.XPATH,
                                 "//div[1]/div[1]/div[2]/div[1]//select")
    Select(select).select_by_value("fragment")

    # 20. Click 'SELECT'
    select = driver.find_element(By.XPATH,
                                 "//div[1]/div[1]/div[2]/div[1]//select")
    select.click()

    # 21. Select the 'skip' option in 'SELECT'
    select = driver.find_element(By.XPATH,
                                 "//div[1]/div[1]/div[2]/div[1]//select")
    Select(select).select_by_value("skip")

    # 22. Click 'SELECT'
    select = driver.find_element(By.XPATH,
                                 "//div[1]/div[1]/div[2]/div[1]//select")
    select.click()

    # 23. Select the 'notes' option in 'SELECT'
    select = driver.find_element(By.XPATH,
                                 "//div[1]/div[1]/div[2]/div[1]//select")
    Select(select).select_by_value("notes")

    # 24. Click 'SELECT1'
    select1 = driver.find_element(By.XPATH,
                                  "//div[2]/div[2]//select")
    select1.click()

    # 25. Select the 'slide' option in 'SELECT1'
    select1 = driver.find_element(By.XPATH,
                                  "//div[2]/div[2]//select")
    Select(select1).select_by_value("slide")

    # 26. Click 'SELECT1'
    select1 = driver.find_element(By.XPATH,
                                  "//div[2]/div[2]//select")
    select1.click()

    # 27. Select the 'subslide' option in 'SELECT1'
    select1 = driver.find_element(By.XPATH,
                                  "//div[2]/div[2]//select")
    Select(select1).select_by_value("subslide")

    # 28. Click 'SELECT1'
    select1 = driver.find_element(By.XPATH,
                                  "//div[2]/div[2]//select")
    select1.click()

    # 29. Select the 'fragment' option in 'SELECT1'
    select1 = driver.find_element(By.XPATH,
                                  "//div[2]/div[2]//select")
    Select(select1).select_by_value("fragment")

    # 30. Click 'SELECT1'
    select1 = driver.find_element(By.XPATH,
                                  "//div[2]/div[2]//select")
    select1.click()

    # 31. Select the 'skip' option in 'SELECT1'
    select1 = driver.find_element(By.XPATH,
                                  "//div[2]/div[2]//select")
    Select(select1).select_by_value("skip")

    # 32. Click 'SELECT1'
    select1 = driver.find_element(By.XPATH,
                                  "//div[2]/div[2]//select")
    select1.click()

    # 33. Select the 'notes' option in 'SELECT1'
    select1 = driver.find_element(By.XPATH,
                                  "//div[2]/div[2]//select")
    Select(select1).select_by_value("notes")

    # 34. Click 'Attachments'
    attachments = driver.find_element(By.XPATH,
                                      "//a[. = 'Attachments']")
    attachments.click()

    # 35. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 36. Click 'Tags'
    tags = driver.find_element(By.XPATH,
                               "//a[. = 'Tags']")
    tags.click()

    # 37. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 38. Click 'Attachments'
    attachments = driver.find_element(By.XPATH,
                                      "//a[. = 'Attachments']")
    attachments.click()

    # 39. Click 'Edit Attachments'
    edit_attachments = driver.find_element(By.XPATH,
                                           "//div[2]/div[2]//button[. = 'Edit Attachments']")
    edit_attachments.click()

    # 40. Click 'I6'
    i6 = driver.find_element(By.XPATH,
                             "//div/div/div/div/div/div/div[3]//i")
    i6.click()

    # 41. Click 'Apply'
    apply = driver.find_element(By.XPATH,
                                "//button[. = 'Apply']")
    apply.click()

    # 42. Click 'Edit Attachments1'
    edit_attachments1 = driver.find_element(By.XPATH,
                                            "//div[4]/div[2]//button[. = 'Edit Attachments']")
    edit_attachments1.click()

    # 43. Click 'I6'
    i6 = driver.find_element(By.XPATH,
                             "//div/div/div/div/div/div/div[3]//i")
    i6.click()

    # 44. Click 'Apply'
    apply = driver.find_element(By.XPATH,
                                "//button[. = 'Apply']")
    apply.click()

    # 45. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 46. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 47. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 48. Click 'Attachments'
    attachments = driver.find_element(By.XPATH,
                                      "//a[. = 'Attachments']")
    attachments.click()

    # 49. Click 'Edit Attachments2'
    edit_attachments2 = driver.find_element(By.XPATH,
                                            "//div[1]/div[2]/div[1]//button[. = 'Edit Attachments']")
    edit_attachments2.click()

    # 50. Click 'Apply'
    apply = driver.find_element(By.XPATH,
                                "//button[. = 'Apply']")
    apply.click()

    # 51. Click 'View1'
    view1 = driver.find_element(By.CSS_SELECTOR,
                                "#viewlink")
    view1.click()

    # 52. Click 'Tags'
    tags = driver.find_element(By.XPATH,
                               "//a[. = 'Tags']")
    tags.click()

    # 53. Click 'Add tag'
    add_tag = driver.find_element(By.XPATH,
                                  "//div[1]/div[2]/div[1]//button[. = 'Add tag']")
    add_tag.click()

    # 54. Click 'INPUT4'
    input4 = driver.find_element(By.XPATH,
                                 "//div[1]/div[2]/div[1]//input")
    input4.click()

    # 55. Type 'test' in 'INPUT4'
    input4 = driver.find_element(By.XPATH,
                                 "//div[1]/div[2]/div[1]//input")
    input4.send_keys("test")

    # 56. Click 'Add tag'
    add_tag = driver.find_element(By.XPATH,
                                  "//div[1]/div[2]/div[1]//button[. = 'Add tag']")
    add_tag.click()

    # 57. Click 'INPUT4'
    input4 = driver.find_element(By.XPATH,
                                 "//div[1]/div[2]/div[1]//input")
    input4.click()

    # 58. Type 'test' in 'INPUT4'
    input4 = driver.find_element(By.XPATH,
                                 "//div[1]/div[2]/div[1]//input")
    input4.send_keys("test")

    # 59. Click 'Add tag'
    add_tag = driver.find_element(By.XPATH,
                                  "//div[1]/div[2]/div[1]//button[. = 'Add tag']")
    add_tag.click()

    # 60. Click 'INPUT4'
    input4 = driver.find_element(By.XPATH,
                                 "//div[1]/div[2]/div[1]//input")
    input4.click()

    # 61. Type 'test' in 'INPUT4'
    input4 = driver.find_element(By.XPATH,
                                 "//div[1]/div[2]/div[1]//input")
    input4.send_keys("test")

    # 62. Click 'Add tag'
    add_tag = driver.find_element(By.XPATH,
                                  "//div[1]/div[2]/div[1]//button[. = 'Add tag']")
    add_tag.click()
