from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Jupyter Notebook Functional Test
    Package: HelpMenu
    Test: Help Menu
    Generated by: Jianpeng Chen (jc107@uowmail.edu.au)
    Generated on 05/05/2021, 12:08:35
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fk3yOvlRsLLpCaaggFfMO8vEplPSx8qsdrnNiqcDOgM",
                              project_name="Jupyter Notebook Functional Test",
                              job_name="Help Menu")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost:8888/tree"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'functional test folder'
    functional_test_folder = driver.find_element(By.XPATH,
                                                 "//span[. = 'functional test folder']")
    functional_test_folder.click()

    # 3. Click 'test_editor_02.ipynb1'
    test_editor_02_ipynb1 = driver.find_element(By.XPATH,
                                                "//span[. = 'test_editor_02.ipynb']")
    test_editor_02_ipynb1.click()

    # 4. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 5. Click 'Help'
    help = driver.find_element(By.XPATH,
                               "//a[. = 'Help']")
    help.click()

    # 6. Click 'User Interface Tour'
    user_interface_tour = driver.find_element(By.XPATH,
                                              "//a[. = 'User Interface Tour']")
    user_interface_tour.click()

    # 7. Click 'DIV9'
    div9 = driver.find_element(By.XPATH,
                               "//div[4]/div/div/div[1]/div[2]")
    div9.click()

    # 8. Click 'Help'
    help = driver.find_element(By.XPATH,
                               "//a[. = 'Help']")
    help.click()

    # 9. Click 'User Interface Tour'
    user_interface_tour = driver.find_element(By.XPATH,
                                              "//a[. = 'User Interface Tour']")
    user_interface_tour.click()

    # 10. Send 'Esc' key(s)
    ActionChains(driver).send_keys(Keys.Esc).perform()

    # 11. Click 'Help'
    help = driver.find_element(By.XPATH,
                               "//a[. = 'Help']")
    help.click()

    # 12. Click 'User Interface Tour'
    user_interface_tour = driver.find_element(By.XPATH,
                                              "//a[. = 'User Interface Tour']")
    user_interface_tour.click()

    # 13. Click 'Help'
    help = driver.find_element(By.XPATH,
                               "//a[. = 'Help']")
    help.click()

    # 14. Click 'User Interface Tour'
    user_interface_tour = driver.find_element(By.XPATH,
                                              "//a[. = 'User Interface Tour']")
    user_interface_tour.click()

    # 15. Click 'Help'
    help = driver.find_element(By.XPATH,
                               "//a[. = 'Help']")
    help.click()

    # 16. Click 'Help'
    help = driver.find_element(By.XPATH,
                               "//a[. = 'Help']")
    help.click()

    # 17. Click 'Notebook Help'
    notebook_help = driver.find_element(By.XPATH,
                                        "//a[. = '\n                                \n                                    \n                                \n\n                                Notebook Help\n                                ']")
    notebook_help.click()

    # 18. Switch to window '2'
    driver.switch_to.window(driver.window_handles[2])

    # 19. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 20. Click 'Help'
    help = driver.find_element(By.XPATH,
                               "//a[. = 'Help']")
    help.click()

    # 21. Click 'Markdown1'
    markdown1 = driver.find_element(By.XPATH,
                                    "//a[. = '\n                                \n                                    \n                                \n\n                                Markdown\n                                ']")
    markdown1.click()

    # 22. Switch to window '3'
    driver.switch_to.window(driver.window_handles[3])

    # 23. Click 'Help'
    help = driver.find_element(By.XPATH,
                               "//a[. = 'Help']")
    help.click()

    # 24. Click 'Python Reference'
    python_reference = driver.find_element(By.XPATH,
                                           "//span[. = 'Python Reference']")
    python_reference.click()

    # 25. Switch to window '4'
    driver.switch_to.window(driver.window_handles[4])

    # 26. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 27. Click 'IPython Reference'
    ipython_reference = driver.find_element(By.XPATH,
                                            "//span[. = 'IPython Reference']")
    ipython_reference.click()

    # 28. Switch to window '5'
    driver.switch_to.window(driver.window_handles[5])

    # 29. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 30. Click 'Help'
    help = driver.find_element(By.XPATH,
                               "//a[. = 'Help']")
    help.click()

    # 31. Click 'NumPy Reference'
    numpy_reference = driver.find_element(By.XPATH,
                                          "//span[. = 'NumPy Reference']")
    numpy_reference.click()

    # 32. Switch to window '6'
    driver.switch_to.window(driver.window_handles[6])

    # 33. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 34. Click 'Help'
    help = driver.find_element(By.XPATH,
                               "//a[. = 'Help']")
    help.click()

    # 35. Click 'SciPy Reference'
    scipy_reference = driver.find_element(By.XPATH,
                                          "//span[. = 'SciPy Reference']")
    scipy_reference.click()

    # 36. Switch to window '7'
    driver.switch_to.window(driver.window_handles[7])

    # 37. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 38. Click 'Help'
    help = driver.find_element(By.XPATH,
                               "//a[. = 'Help']")
    help.click()

    # 39. Click 'Matplotlib Reference'
    matplotlib_reference = driver.find_element(By.XPATH,
                                               "//span[. = 'Matplotlib Reference']")
    matplotlib_reference.click()

    # 40. Switch to window '8'
    driver.switch_to.window(driver.window_handles[8])

    # 41. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 42. Click 'Help'
    help = driver.find_element(By.XPATH,
                               "//a[. = 'Help']")
    help.click()

    # 43. Click 'SymPy Reference'
    sympy_reference = driver.find_element(By.XPATH,
                                          "//span[. = 'SymPy Reference']")
    sympy_reference.click()

    # 44. Switch to window '9'
    driver.switch_to.window(driver.window_handles[9])

    # 45. Switch to window '1'
    driver.switch_to.window(driver.window_handles[1])

    # 46. Click 'Help'
    help = driver.find_element(By.XPATH,
                               "//a[. = 'Help']")
    help.click()

    # 47. Click 'pandas Reference'
    pandas_reference = driver.find_element(By.XPATH,
                                           "//span[. = 'pandas Reference']")
    pandas_reference.click()

    # 48. Switch to window '10'
    driver.switch_to.window(driver.window_handles[10])

    # 49. Click 'Help'
    help = driver.find_element(By.XPATH,
                               "//a[. = 'Help']")
    help.click()

    # 50. Click 'About'
    about = driver.find_element(By.CSS_SELECTOR,
                                "#notebook_about")
    about.click()

    # 51. Click 'OK6'
    ok6 = driver.find_element(By.XPATH,
                              "//button[. = 'OK']")
    ok6.click()

    # 52. Click 'Help'
    help = driver.find_element(By.XPATH,
                               "//a[. = 'Help']")
    help.click()

    # 53. Click 'About'
    about = driver.find_element(By.CSS_SELECTOR,
                                "#notebook_about")
    about.click()

    # 54. Click '×'
    _ = driver.find_element(By.XPATH,
                            "//div[9]//button[. = '×']")
    _.click()
